DROP VIEW sys_all_views_dep_view_vu_prepare
GO

DROP PROC sys_all_views_dep_proc_vu_prepare
GO

DROP FUNCTION sys_all_views_dep_func_vu_prepare
GO

DROP VIEW sys_all_views_select_vu_prepare
GO

DROP VIEW sys_all_views_select_chk_option_vu_prepare
GO

DROP TABLE sys_all_views_table_vu_prepare
GO
