name: 'Run JDBC Tests with database level collation'
description: 'Run Babel JDBC test framework with database level collation'

inputs:
  input_dir:
    description: 'Test input directory'
    required: no
    default: input

runs:
  using: "composite"
  steps:
    - name: Run JDBC Tests with db level collation
      run: |
          export PATH=/opt/mssql-tools/bin:$PATH
          sqlcmd -S localhost -U "jdbc_user" -P 12345678 -i .github/scripts/db_collation.sql
          export PATH=~/${{env.INSTALL_DIR}}/bin:$PATH
          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
          export inputFilesPath=${{inputs.input_dir}}
          cd test/JDBC/
          sudo sed -i "s/databaseName = master/databaseName = test_db_collation/g" src/main/resources/config.txt
          sudo sed -i "s/databaseCollationName = default/databaseCollationName = bbf_unicode_cp1_ci_ai/g" src/main/resources/config.txt
          mvn test
      shell: bash
