name: 'Run JDBC Tests with db level collation'
description: 'Run Babel JDBC test framework'

inputs:
  input_dir:
    description: 'Test input directory'
    required: no
    default: input

runs:
  using: "composite"
  steps:
    - name: Run JDBC Tests with db level collation
      run: |
          echo $pwd
          ls
          sudo ~/psql/bin/psql -v ON_ERROR_STOP=1 -d postgres -U runner -p ${{inputs.psql_port}}  user="jdbc_user"  db="jdbc_testdb"  migration_mode=${{inputs.migration_mode}}  tsql_port=${{inputs.tsql_port}}  parallel_query_mode=${{inputs.parallel_query_mode}} -f .github/scripts/db_collation.sql
          export PATH=~/${{env.INSTALL_DIR}}/bin:$PATH
          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
          export inputFilesPath=${{inputs.input_dir}}
          cd test/JDBC/
          sudo sed -i "s/databaseName = master/databaseName = test_db_collation/g" src/main/resources/config.txt
          mvn test
      shell: bash
