name: 'Run JDBC Tests'
description: 'Run Babel JDBC test framework'

inputs:
  input_dir:
    description: 'Test input directory'
    required: no
    default: input
  migration_mode:
    description: 'Database migration mode'
    required: no
    default: "multi-db"

runs:
  using: "composite"
  steps:
    - name: Run JDBC Tests
      run: |
          export PATH=~/${{env.INSTALL_DIR}}/bin:$PATH
          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
          export inputFilesPath=${{inputs.input_dir}}
          cd test/JDBC/
          if [[ '${{ inputs.migration_mode }}' == 'single-db' ]];then
            export isSingleDbMode=true
            mvn test
            unset isSingleDbMode
          else
            mvn test
          fi
      shell: bash
