-- TBL_LOCATION_TREE_SPACE_1
CREATE TABLE [dbo].[TBL_LOCATION_TREE_SPACE_1] (
    [PK_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [NODE_PATH]     NVARCHAR (255) NOT NULL,
    [LAST_MODIFIED] DATETIME       NOT NULL,
    [LEVEL1_ID]     INT            NULL,
    [LEVEL2_ID]     INT            NULL,
    [LEVEL3_ID]     INT            NULL,
    [LEVEL4_ID]     INT            NULL,
    [LEVEL5_ID]     INT            NULL,
    [LEVEL6_ID]     INT            NULL,
    [LEVEL7_ID]     INT            NULL,
    [LEVEL8_ID]     INT            NULL,
    [LEVEL1_NAME]   NVARCHAR (255) NULL,
    [LEVEL2_NAME]   NVARCHAR (255) NULL,
    [LEVEL3_NAME]   NVARCHAR (255) NULL,
    [LEVEL4_NAME]   NVARCHAR (255) NULL,
    [LEVEL5_NAME]   NVARCHAR (255) NULL,
    [LEVEL6_NAME]   NVARCHAR (255) NULL,
    [LEVEL7_NAME]   NVARCHAR (255) NULL,
    [LEVEL8_NAME]   NVARCHAR (255) NULL,
	[FTI] NVARCHAR(MAX) NULL,
    [PATH_LEN]      INT NULL, -- For DMS load - replaces computed column
    CONSTRAINT [PK_TBL_LOCATION_TREE_SPACE_1] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_TBL_LOCATION_TREE_SPACE_1_NODE_PATH]
    ON [dbo].[TBL_LOCATION_TREE_SPACE_1]([NODE_PATH] ASC);
GO

-- TBL_LOCATION_TREE_SPACE_2
CREATE TABLE [dbo].[TBL_LOCATION_TREE_SPACE_2] (
    [PK_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [NODE_PATH]     NVARCHAR (255) NOT NULL,
    [LAST_MODIFIED] DATETIME       NOT NULL,
    [LEVEL1_ID]     INT            NULL,
    [LEVEL2_ID]     INT            NULL,
    [LEVEL3_ID]     INT            NULL,
    [LEVEL4_ID]     INT            NULL,
    [LEVEL5_ID]     INT            NULL,
    [LEVEL6_ID]     INT            NULL,
    [LEVEL7_ID]     INT            NULL,
    [LEVEL8_ID]     INT            NULL,
    [LEVEL1_NAME]   NVARCHAR (255) NULL,
    [LEVEL2_NAME]   NVARCHAR (255) NULL,
    [LEVEL3_NAME]   NVARCHAR (255) NULL,
    [LEVEL4_NAME]   NVARCHAR (255) NULL,
    [LEVEL5_NAME]   NVARCHAR (255) NULL,
    [LEVEL6_NAME]   NVARCHAR (255) NULL,
    [LEVEL7_NAME]   NVARCHAR (255) NULL,
    [LEVEL8_NAME]   NVARCHAR (255) NULL,
	[FTI] NVARCHAR(MAX) NULL,
    [PATH_LEN]      INT NULL, -- For DMS load - replaces computed column
    CONSTRAINT [PK_TBL_LOCATION_TREE_SPACE_2] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_TBL_LOCATION_TREE_SPACE_2_NODE_PATH]
    ON [dbo].[TBL_LOCATION_TREE_SPACE_2]([NODE_PATH] ASC);
GO

-- TBL_LOCATION_TREE_SPACE_3
CREATE TABLE [dbo].[TBL_LOCATION_TREE_SPACE_3] (
    [PK_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [NODE_PATH]     NVARCHAR (255) NOT NULL,
    [LAST_MODIFIED] DATETIME       NOT NULL,
    [LEVEL1_ID]     INT            NULL,
    [LEVEL2_ID]     INT            NULL,
    [LEVEL3_ID]     INT            NULL,
    [LEVEL4_ID]     INT            NULL,
    [LEVEL5_ID]     INT            NULL,
    [LEVEL6_ID]     INT            NULL,
    [LEVEL7_ID]     INT            NULL,
    [LEVEL8_ID]     INT            NULL,
    [LEVEL1_NAME]   NVARCHAR (255) NULL,
    [LEVEL2_NAME]   NVARCHAR (255) NULL,
    [LEVEL3_NAME]   NVARCHAR (255) NULL,
    [LEVEL4_NAME]   NVARCHAR (255) NULL,
    [LEVEL5_NAME]   NVARCHAR (255) NULL,
    [LEVEL6_NAME]   NVARCHAR (255) NULL,
    [LEVEL7_NAME]   NVARCHAR (255) NULL,
    [LEVEL8_NAME]   NVARCHAR (255) NULL,
	[FTI] NVARCHAR(MAX) NULL,
    [PATH_LEN]      INT NULL, -- For DMS load - replaces computed column
    CONSTRAINT [PK_TBL_LOCATION_TREE_SPACE_3] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_TBL_LOCATION_TREE_SPACE_3_NODE_PATH]
    ON [dbo].[TBL_LOCATION_TREE_SPACE_3]([NODE_PATH] ASC);
GO

-- TBL_LOCATION_TREE_SPACE_4
CREATE TABLE [dbo].[TBL_LOCATION_TREE_SPACE_4] (
    [PK_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [NODE_PATH]     NVARCHAR (255) NOT NULL,
    [LAST_MODIFIED] DATETIME       NOT NULL,
    [LEVEL1_ID]     INT            NULL,
    [LEVEL2_ID]     INT            NULL,
    [LEVEL3_ID]     INT            NULL,
    [LEVEL4_ID]     INT            NULL,
    [LEVEL5_ID]     INT            NULL,
    [LEVEL6_ID]     INT            NULL,
    [LEVEL7_ID]     INT            NULL,
    [LEVEL8_ID]     INT            NULL,
    [LEVEL1_NAME]   NVARCHAR (255) NULL,
    [LEVEL2_NAME]   NVARCHAR (255) NULL,
    [LEVEL3_NAME]   NVARCHAR (255) NULL,
    [LEVEL4_NAME]   NVARCHAR (255) NULL,
    [LEVEL5_NAME]   NVARCHAR (255) NULL,
    [LEVEL6_NAME]   NVARCHAR (255) NULL,
    [LEVEL7_NAME]   NVARCHAR (255) NULL,
    [LEVEL8_NAME]   NVARCHAR (255) NULL,
	[FTI] NVARCHAR(MAX) NULL,
    [PATH_LEN]      INT NULL, -- For DMS load - replaces computed column
    CONSTRAINT [PK_TBL_LOCATION_TREE_SPACE_4] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_TBL_LOCATION_TREE_SPACE_4_NODE_PATH]
    ON [dbo].[TBL_LOCATION_TREE_SPACE_4]([NODE_PATH] ASC);
GO

-- TBL_LOCATION_TREE_SPACE_5
CREATE TABLE [dbo].[TBL_LOCATION_TREE_SPACE_5] (
    [PK_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [NODE_PATH]     NVARCHAR (255) NOT NULL,
    [LAST_MODIFIED] DATETIME       NOT NULL,
    [LEVEL1_ID]     INT            NULL,
    [LEVEL2_ID]     INT            NULL,
    [LEVEL3_ID]     INT            NULL,
    [LEVEL4_ID]     INT            NULL,
    [LEVEL5_ID]     INT            NULL,
    [LEVEL6_ID]     INT            NULL,
    [LEVEL7_ID]     INT            NULL,
    [LEVEL8_ID]     INT            NULL,
    [LEVEL1_NAME]   NVARCHAR (255) NULL,
    [LEVEL2_NAME]   NVARCHAR (255) NULL,
    [LEVEL3_NAME]   NVARCHAR (255) NULL,
    [LEVEL4_NAME]   NVARCHAR (255) NULL,
    [LEVEL5_NAME]   NVARCHAR (255) NULL,
    [LEVEL6_NAME]   NVARCHAR (255) NULL,
    [LEVEL7_NAME]   NVARCHAR (255) NULL,
    [LEVEL8_NAME]   NVARCHAR (255) NULL,
	[FTI] NVARCHAR(MAX) NULL,
    [PATH_LEN]      INT NULL, -- For DMS load - replaces computed column
    CONSTRAINT [PK_TBL_LOCATION_TREE_SPACE_5] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_TBL_LOCATION_TREE_SPACE_5_NODE_PATH]
    ON [dbo].[TBL_LOCATION_TREE_SPACE_5]([NODE_PATH] ASC);
GO

CREATE FUNCTION [dbo].[FN_SPLIT_STRING]
(
    @string NVARCHAR(MAX),
    @delimiter CHAR(1)
)
RETURNS @output TABLE(splitdata NVARCHAR(MAX)
)
BEGIN
    DECLARE @start INT, @end INT
    SELECT @start = 1, @end = CHARINDEX(@delimiter, @string)
    WHILE @start < LEN(@string) + 1 BEGIN
        IF @end = 0
            SET @end = LEN(@string) + 1

        INSERT INTO @output (splitdata)
        VALUES(SUBSTRING(@string, @start, @end - @start))
        SET @start = @end + 1
        SET @end = CHARINDEX(@delimiter, @string, @start)

    END
    RETURN
END
GO

CREATE FUNCTION [dbo].[FN_SPLIT_STRING_WITH_ORDINAL]
(
    @string NVARCHAR(MAX),
    @delimiter CHAR(1)
)
RETURNS @output TABLE
(
    ordinal INT,
    splitdata NVARCHAR(MAX)
)
BEGIN
    DECLARE @start INT, @end INT, @index INT = 1;
    SELECT @start = 1, @end = CHARINDEX(@delimiter, @string);

    WHILE @start < LEN(@string) + 1
    BEGIN
        IF @end = 0
            SET @end = LEN(@string) + 1;

        INSERT INTO @output (Ordinal, splitdata)
        VALUES (@index, SUBSTRING(@string, @start, @end - @start));

        SET @start = @end + 1;
        SET @end = CHARINDEX(@delimiter, @string, @start);
        SET @index += 1;
    END

    RETURN;
END
GO

CREATE PROCEDURE dbo.CREATE_FTI_COLUMNS
	@SEARCHABLE_COLUMNS NVARCHAR(MAX)
AS
	SET NOCOUNT ON;
	DECLARE @SEARCHABLE_COLUMN_LIST_TABLE TABLE(Ordinal INT, COL_LIST_STR NVARCHAR(255));
	INSERT INTO @SEARCHABLE_COLUMN_LIST_TABLE (Ordinal, COL_LIST_STR) SELECT ordinal, splitdata  FROM dbo.FN_SPLIT_STRING_WITH_ORDINAL(@SEARCHABLE_COLUMNS, '^');


	DECLARE @TREE_INDEX INT = 1;
	DECLARE @COL_LIST_STR NVARCHAR(255)
	DECLARE COL_LIST_CURSOR CURSOR FOR
	SELECT COL_LIST_STR FROM @SEARCHABLE_COLUMN_LIST_TABLE ORDER BY Ordinal
	OPEN COL_LIST_CURSOR

	FETCH NEXT FROM COL_LIST_CURSOR INTO @COL_LIST_STR

	WHILE @@FETCH_STATUS = 0
		BEGIN
			DECLARE @TREE_SEACHABLE_COLUMN_TABLE TABLE(COL NVARCHAR(255));
			DECLARE @COL_INDEX NVARCHAR(255);
			DECLARE @SQL NVARCHAR(MAX);
			DECLARE @SQL1 NVARCHAR(MAX);
			DECLARE @TABLE_NAME NVARCHAR(255);
			DECLARE @COLUMN_NAME NVARCHAR(255);

			SELECT @TABLE_NAME = 'TBL_LOCATION_TREE_SPACE_' + CAST(@TREE_INDEX AS NVARCHAR(10));

			DELETE FROM @TREE_SEACHABLE_COLUMN_TABLE;
			INSERT INTO @TREE_SEACHABLE_COLUMN_TABLE SELECT * FROM dbo.FN_SPLIT_STRING(@COL_LIST_STR, '|');

			DECLARE TREE_SEACHABLE_COLUMN_CURSOR CURSOR FOR
			SELECT COL FROM @TREE_SEACHABLE_COLUMN_TABLE order by COL


			OPEN TREE_SEACHABLE_COLUMN_CURSOR
			FETCH NEXT FROM TREE_SEACHABLE_COLUMN_CURSOR INTO @COL_INDEX

			SELECT @SQL = '';
			WHILE @@FETCH_STATUS = 0
				BEGIN
					--PRINT @COL_INDEX
					IF @COL_INDEX > 0
						BEGIN
							SELECT @COLUMN_NAME = 'LEVEL' + @COL_INDEX + '_NAME';
							IF LEN(@SQL) > 0
								BEGIN
									SELECT @SQL = @SQL + ' + ';
								END
							SELECT @SQL = @SQL + 'COALESCE(IIF(' + @COLUMN_NAME + ' = '''', NULL, ' + @COLUMN_NAME + ') + '' '', '''')';
						END
					FETCH NEXT FROM TREE_SEACHABLE_COLUMN_CURSOR INTO @COL_INDEX
				END
			SELECT @SQL = LTRIM(RTRIM(@SQL));
			IF LEN(@SQL) = 0
				BEGIN
					SELECT @SQL = '''''';
				END
				SELECT @SQL1 = 'IF COL_LENGTH(''' +  @TABLE_NAME + ''', ''FTI'') IS NOT NULL BEGIN ALTER TABLE ' + @TABLE_NAME + ' DROP COLUMN FTI END';
				-- PRINT @SQL1;
				EXECUTE SP_EXECUTESQL @SQL1;

				SELECT @SQL = CONCAT('ALTER TABLE ', @TABLE_NAME, ' ADD FTI AS (', @SQL, ') PERSISTED;');
				-- PRINT @SQL;
				EXECUTE SP_EXECUTESQL @SQL;
			CLOSE TREE_SEACHABLE_COLUMN_CURSOR
			DEALLOCATE TREE_SEACHABLE_COLUMN_CURSOR

			SELECT @TREE_INDEX = @TREE_INDEX + 1;
			FETCH NEXT FROM COL_LIST_CURSOR INTO @COL_LIST_STR
		END
	CLOSE COL_LIST_CURSOR;
	DEALLOCATE COL_LIST_CURSOR;
	SET NOCOUNT OFF;
GO