/*-------------------------------------------------------------------------
 *
 * pltsql_nodetags.h
 *    Generated node infrastructure code
 *
 * Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by gen_pltsql_node_support.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PLTSQL_NODETAGS_H
#define PLTSQL_NODETAGS_H

/* PLtsql NodeTag start offset — used by is_pltsql_node() checks */
#define PLTSQL_NODETAG_START 1000

/*
 * PLtsql NodeTag values, auto-generated by gen_pltsql_node_support.pl.
 * Offset from 1000 to avoid collision with engine NodeTags.
 */

#define T_PLtsql_type ((NodeTag) 1000)
#define T_PLtsql_expr ((NodeTag) 1001)
#define T_PLtsql_datum ((NodeTag) 1002)
#define T_PLtsql_variable ((NodeTag) 1003)
#define T_PLtsql_var ((NodeTag) 1004)
#define T_PLtsql_row ((NodeTag) 1005)
#define T_PLtsql_rec ((NodeTag) 1006)
#define T_PLtsql_tbl ((NodeTag) 1007)
#define T_PLtsql_recfield ((NodeTag) 1008)
#define T_PLtsql_arrayelem ((NodeTag) 1009)
#define T_PLtsql_nsitem ((NodeTag) 1010)
#define T_PLtsql_stmt ((NodeTag) 1011)
#define T_PLtsql_condition ((NodeTag) 1012)
#define T_PLtsql_exception_block ((NodeTag) 1013)
#define T_PLtsql_exception ((NodeTag) 1014)
#define T_PLtsql_stmt_block ((NodeTag) 1015)
#define T_PLtsql_stmt_assign ((NodeTag) 1016)
#define T_PLtsql_stmt_perform ((NodeTag) 1017)
#define T_PLtsql_stmt_call ((NodeTag) 1018)
#define T_PLtsql_stmt_commit ((NodeTag) 1019)
#define T_PLtsql_stmt_rollback ((NodeTag) 1020)
#define T_PLtsql_stmt_set ((NodeTag) 1021)
#define T_PLtsql_diag_item ((NodeTag) 1022)
#define T_PLtsql_stmt_getdiag ((NodeTag) 1023)
#define T_PLtsql_stmt_if ((NodeTag) 1024)
#define T_PLtsql_if_elsif ((NodeTag) 1025)
#define T_PLtsql_stmt_case ((NodeTag) 1026)
#define T_PLtsql_case_when ((NodeTag) 1027)
#define T_PLtsql_stmt_loop ((NodeTag) 1028)
#define T_PLtsql_stmt_while ((NodeTag) 1029)
#define T_PLtsql_stmt_fori ((NodeTag) 1030)
#define T_PLtsql_stmt_forq ((NodeTag) 1031)
#define T_PLtsql_stmt_fors ((NodeTag) 1032)
#define T_PLtsql_stmt_forc ((NodeTag) 1033)
#define T_PLtsql_stmt_dynfors ((NodeTag) 1034)
#define T_PLtsql_stmt_foreach_a ((NodeTag) 1035)
#define T_PLtsql_stmt_open ((NodeTag) 1036)
#define T_PLtsql_stmt_fetch ((NodeTag) 1037)
#define T_PLtsql_stmt_close ((NodeTag) 1038)
#define T_PLtsql_stmt_exit ((NodeTag) 1039)
#define T_PLtsql_stmt_insert_bulk ((NodeTag) 1040)
#define T_PLtsql_stmt_dbcc ((NodeTag) 1041)
#define T_PLtsql_stmt_return ((NodeTag) 1042)
#define T_PLtsql_stmt_return_next ((NodeTag) 1043)
#define T_PLtsql_stmt_return_query ((NodeTag) 1044)
#define T_PLtsql_stmt_raise ((NodeTag) 1045)
#define T_PLtsql_raise_option ((NodeTag) 1046)
#define T_PLtsql_stmt_grantdb ((NodeTag) 1047)
#define T_PLtsql_stmt_change_dbowner ((NodeTag) 1048)
#define T_PLtsql_stmt_alter_db ((NodeTag) 1049)
#define T_PLtsql_stmt_fulltextindex ((NodeTag) 1050)
#define T_PLtsql_stmt_grantschema ((NodeTag) 1051)
#define T_PLtsql_stmt_partition_function ((NodeTag) 1052)
#define T_PLtsql_stmt_partition_scheme ((NodeTag) 1053)
#define T_PLtsql_stmt_assert ((NodeTag) 1054)
#define T_PLtsql_txn_data ((NodeTag) 1055)
#define T_PLtsql_stmt_execsql ((NodeTag) 1056)
#define T_PLtsql_stmt_set_explain_mode ((NodeTag) 1057)
#define T_PLtsql_stmt_dynexecute ((NodeTag) 1058)
#define T_PLtsql_stmt_print ((NodeTag) 1059)
#define T_PLtsql_stmt_kill ((NodeTag) 1060)
#define T_PLtsql_stmt_init ((NodeTag) 1061)
#define T_PLtsql_stmt_try_catch ((NodeTag) 1062)
#define T_PLtsql_stmt_query_set ((NodeTag) 1063)
#define T_PLtsql_stmt_push_result ((NodeTag) 1064)
#define T_PLtsql_stmt_exec ((NodeTag) 1065)
#define T_tsql_exec_param ((NodeTag) 1066)
#define T_PLtsql_stmt_exec_sp ((NodeTag) 1067)
#define T_PLtsql_stmt_decl_table ((NodeTag) 1068)
#define T_PLtsql_stmt_exec_batch ((NodeTag) 1069)
#define T_PLtsql_stmt_raiserror ((NodeTag) 1070)
#define T_PLtsql_stmt_throw ((NodeTag) 1071)
#define T_PLtsql_stmt_deallocate ((NodeTag) 1072)
#define T_PLtsql_stmt_decl_cursor ((NodeTag) 1073)
#define T_PLtsql_stmt_goto ((NodeTag) 1074)
#define T_PLtsql_stmt_label ((NodeTag) 1075)
#define T_PLtsql_stmt_usedb ((NodeTag) 1076)
#define T_PLtsql_stmt_save_ctx ((NodeTag) 1077)
#define T_PLtsql_stmt_restore_ctx_full ((NodeTag) 1078)
#define T_PLtsql_stmt_restore_ctx_partial ((NodeTag) 1079)

#endif /* PLTSQL_NODETAGS_H */
