DROP VIEW test_babelfish_namespace_ext_view
GO

DROP PROC test_babelfish_namespace_ext_proc
GO

DROP FUNCTION test_babelfish_namespace_ext_func
GO

DROP SCHEMA test_babelfish_namespace_ext_sch1
GO

DROP SCHEMA test_babelfish_namespace_ext_sch2
GO
