DROP VIEW babelfish_sysdatabases_vu_prepare_view
GO

DROP PROC babelfish_sysdatabases_vu_prepare_proc
GO

DROP FUNCTION babelfish_sysdatabases_vu_prepare_func
GO

DROP DATABASE babelfish_sysdatabases_vu_prepare_db
GO
