DROP VIEW sys_server_principals_dep_for_13_x_vu_prepare_view
GO

DROP PROC sys_server_principals_dep_for_13_x_vu_prepare_proc
GO

DROP FUNCTION sys_server_principals_dep_for_13_x_vu_prepare_func
GO

DROP LOGIN sys_server_principals_dep_for_13_x_vu_prepare_login1
GO

DROP LOGIN sys_server_principals_dep_for_13_x_vu_prepare_login2
GO

