DROP VIEW database_principals_dep_vu_prepare_view
GO

DROP PROC database_principals_dep_vu_prepare_proc
GO

DROP FUNCTION database_principals_dep_vu_prepare_func
GO

DROP USER database_principals_dep_vu_prepare_user1
GO

DROP USER database_principals_dep_vu_prepare_user2
GO

DROP LOGIN database_principals_dep_vu_prepare_login1
GO

DROP LOGIN database_principals_dep_vu_prepare_login2
GO

