name: 'Setup Upgrade Version Composite Action'

runs:
  using: "composite"
  steps:
    - name: setup upgrade version composite action
      run: |
        LEN=$(yq -r '."upgrade-version" | length' ${{ github.workspace }}/.github/configuration/upgrade-test-configuration.yml)
        if [[ $LEN -le 1 ]]
        then
            echo "ERROR: Upgrade path length less than 2" 1>&2
            exit 1
        fi
        mkdir ${{ github.workspace }}/.github/composite-actions/upgrade-version
        touch ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
        printf 'name: Upgrade and Test \nruns: \n  using: "composite"\n  steps:\n' > ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
        for (( i=1 ; i<$LEN ; i++ )); 
        do
            version_var=".\"upgrade-version\"[$i]" 
            next_upgrade_version=$(yq -r $version_var ${{ github.workspace }}/.github/configuration/upgrade-test-configuration.yml)
            next_upgrade_version_engb=".\""${next_upgrade_version}"\".engine_branch"
            engine_branch=$(yq -r $next_upgrade_version_engb ${{ github.workspace }}/.github/template/version-branch-template.yml)
            next_upgrade_version_extb=".\""${next_upgrade_version}"\".extension_branch"
            extension_branch=$(yq -r $next_upgrade_version_extb ${{ github.workspace }}/.github/template/version-branch-template.yml)
            is_final_ver=false; [[ i -eq $LEN-1 ]] && is_final_ver=true
            sudo cat ${{ github.workspace }}/.github/template/upgrade-version-template.yml >> ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml

            sed -i "s/name: Upgrade Version to #/name: Upgrade Version to $next_upgrade_version/g" ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
            sed -i "s/id: upgrade-version-#/id: upgrade-version-$i/g" ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
            temp="\&\& steps.upgrade-version-$(($i-1)).outcome == 'success'"; [[ i -eq 1 ]] && temp=""
            sed -i "s/#if: always()/if: always() $temp/g" ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
            sed -i "s/engine_branch: #/engine_branch: ${engine_branch}/g" ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
            sed -i "s/extension_branch: #/extension_branch: ${extension_branch}/g" ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
            sed -i "s/is_final_ver: #/is_final_ver: ${is_final_ver}/g" ${{ github.workspace }}/.github/composite-actions/upgrade-version/action.yml
        done
      shell: bash
          
          