DROP VIEW ATTIMEZONE_dep_vu_prepare_v1
GO

DROP VIEW ATTIMEZONE_dep_vu_prepare_v2
GO

DROP PROCEDURE ATTIMEZONE_dep_vu_prepare_p1
GO

DROP PROCEDURE ATTIMEZONE_dep_vu_prepare_p2
GO

DROP FUNCTION ATTIMEZONE_dep_vu_prepare_f1()
GO

DROP FUNCTION ATTIMEZONE_dep_vu_prepare_f2()
GO
