DROP VIEW babelfish_authid_user_ext_vu_prepare_view
GO

DROP PROC babelfish_authid_user_ext_vu_prepare_proc
GO

DROP FUNCTION babelfish_authid_user_ext_vu_prepare_func
GO

DROP USER babelfish_authid_user_ext_vu_prepare_user1
GO

DROP USER babelfish_authid_user_ext_vu_prepare_user2
GO

DROP LOGIN babelfish_authid_user_ext_vu_prepare_login1
GO

DROP LOGIN babelfish_authid_user_ext_vu_prepare_login2
GO
