CREATE VIEW BABEL_323_vu_prepare_v1 as (SELECT CONVERT(DATETIME, 1))
GO

CREATE VIEW BABEL_323_vu_prepare_v2 as (SELECT CONVERT(DATETIME, 0.01))
GO

CREATE VIEW BABEL_323_vu_prepare_v3 as (SELECT CONVERT(DATETIME, CAST(1 AS BIGINT)))
GO

CREATE VIEW BABEL_323_vu_prepare_v4 as (SELECT CONVERT(DATETIME, CAST(1 AS TINYINT)))
GO

CREATE VIEW BABEL_323_vu_prepare_v5 as (SELECT CONVERT(DATETIME, CAST(1 AS BIT)))
GO

CREATE VIEW BABEL_323_vu_prepare_v6 as (SELECT CAST(1 AS DATETIME))
GO

CREATE VIEW BABEL_323_vu_prepare_v7 as (SELECT DATEADD(dd, 1, CAST('2020/6/14' AS DATETIME)))
GO

CREATE VIEW BABEL_323_vu_prepare_v8 as (SELECT DATEDIFF(dd, 1, CAST('2020/6/14' AS DATETIME)))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p1 AS (SELECT CONVERT(DATETIME, 1))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p2 AS (SELECT CONVERT(DATETIME, 0.01))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p3 AS (SELECT CONVERT(DATETIME, CAST(1 AS BIGINT)))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p4 AS (SELECT CONVERT(DATETIME, CAST(1 AS TINYINT)))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p5 AS (SELECT CONVERT(DATETIME, CAST(1 AS BIT)))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p6 AS (SELECT CAST(1 AS DATETIME))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p7 AS (SELECT DATEADD(dd, 1, CAST('2020/6/14' AS DATETIME)))
GO

CREATE PROCEDURE BABEL_323_vu_prepare_p8 AS (SELECT DATEDIFF(dd, 1, CAST('2020/6/14' AS DATETIME)))
GO

CREATE FUNCTION BABEL_323_vu_prepare_f1()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT CONVERT(DATETIME, 1));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f2()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT CONVERT(DATETIME, 0.01));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f3()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT CONVERT(DATETIME, CAST(1 AS BIGINT)));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f4()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT CONVERT(DATETIME, CAST(1 AS TINYINT)));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f5()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT CONVERT(DATETIME, CAST(1 AS BIT)));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f6()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT CONVERT(DATETIME, CAST(1 AS DATETIME)));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f7()
RETURNS DATETIME AS
BEGIN
RETURN (SELECT DATEADD(dd, 1, CAST('2020/6/14' AS DATETIME)));
END
GO

CREATE FUNCTION BABEL_323_vu_prepare_f8()
RETURNS INT AS
BEGIN
RETURN (SELECT DATEDIFF(dd, 1, CAST('2020/6/14' AS DATETIME)));
END
GO

DECLARE @v DATETIME
SET @v = 3
GO
