-- cleanup
use babel_sp_special_columns_vu_prepare_db1
go
drop table babel_sp_special_columns_vu_prepare_t1
go
drop table babel_sp_special_columns_vu_prepare_t2
go
drop table babel_sp_special_columns_vu_prepare_t3
go
drop table babel_sp_special_columns_vu_prepare_t4
go
drop table babel_sp_special_columns_vu_prepare_t5
go
drop table babel_sp_special_columns_vu_prepare_MyTable1
go
drop table [babel_sp_special_columns_vu_prepare_MyTable2]
go
drop type babel_sp_special_columns_vu_prepare_eyedees
go
drop type babel_sp_special_columns_vu_prepare_phone_num
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_bigint
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_binary
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_bit
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_char
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_date
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_datetime
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_datetime2
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_datetimeoffset
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_decimal
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_float
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_int
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_money
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_nchar
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_numeric
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_nvarchar
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_real
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_smalldatetime
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_smallint
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_smallmoney
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_sql_variant 
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_sysname
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_time 
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_tinyint
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_uniqueidentifier
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_varbinary
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_varchar
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_int_identity
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_bigint_identity
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_smallint_identity
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_tinyint_identity
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_decimal_identity
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_numeric_identity
go
DROP TABLE babel_sp_special_columns_vu_prepare_unique_idx_table1
go
DROP TABLE babel_sp_special_columns_vu_prepare_unique_idx_table2
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_decimal_5_2
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_decimal_5_3
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_float_7
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_char_7
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_varchar_7
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_nchar_7
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_nvarchar_7
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_time_6
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_datetime2_6
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_datetimeoffset_6
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_binary_7
go
DROP TABLE babel_sp_special_columns_vu_prepare_type_varbinary_7
go
DROP TABLE dbo.tidentityintbig
go
DROP TABLE dbo.tidentityintbigmulti
go
use master
go
drop database babel_sp_special_columns_vu_prepare_db1
go
