DROP VIEW babel_index_nulls_order_before_15_5_a_v1
go
DROP VIEW babel_index_nulls_order_before_15_5_a_v2
go
DROP VIEW babel_index_nulls_order_before_15_5_a_v3
go
DROP VIEW babel_index_nulls_order_before_15_5_b_v1
go
DROP VIEW babel_index_nulls_order_before_15_5_b_v2
go
DROP VIEW babel_index_nulls_order_before_15_5_b_v3
go
DROP VIEW babel_index_nulls_order_before_15_5_ab_v1
go
DROP VIEW babel_index_nulls_order_before_15_5_ab_v2
go
DROP VIEW babel_index_nulls_order_before_15_5_ab_v3
go
DROP VIEW babel_index_nulls_order_before_15_5_ab_v4
go
DROP VIEW babel_index_nulls_order_before_15_5_ab_v5
go
DROP VIEW babel_index_nulls_order_before_15_5_ab_v6
go

DROP TABLE babel_index_nulls_order_before_15_5_tbl
go
