use babel_sp_fkeys_vu_prepare_db1
go
drop table babel_sp_fkeys_vu_prepare_t2
go
drop table babel_sp_fkeys_vu_prepare_t1
go
drop table babel_sp_fkeys_vu_prepare_t4
go
drop table [babel_sp_fkeys_vu_prepare_MyTable7]
go
drop table babel_sp_fkeys_vu_prepare_MyTable6
go
drop table babel_sp_fkeys_vu_prepare_MyTable5
go
drop table babel_sp_fkeys_vu_prepare_t3
go
use master
go
drop table babel_sp_fkeys_vu_prepare_t4
go
drop table babel_sp_fkeys_vu_prepare_t3
go
drop database babel_sp_fkeys_vu_prepare_db1
go
