DROP PROCEDURE IF EXISTS babel_4529_stats
GO

DROP PROCEDURE IF EXISTS babel_4529_dm_exec_connections
GO

DROP PROCEDURE IF EXISTS babel_4529_syscolumns
GO

DROP PROCEDURE IF EXISTS babel_4529_system_objects
GO

DROP PROCEDURE IF EXISTS babel_4529_xml_indexes
GO

DROP PROCEDURE IF EXISTS babel_4529_sysforeignkeys
GO

DROP PROCEDURE IF EXISTS babel_4529_data_spaces
GO

DROP PROCEDURE IF EXISTS babel_4529_sysprocesses
GO

DROP PROCEDURE IF EXISTS babel_4529_key_constraints
GO

DROP PROCEDURE IF EXISTS babel_4529_foreign_keys
GO

DROP PROCEDURE IF EXISTS babel_4529_sysviews
GO

DROP PROCEDURE IF EXISTS babel_4529_systables
GO

DROP PROCEDURE IF EXISTS babel_4529_default_constraints
GO

DROP PROCEDURE IF EXISTS babel_4529_check_constraints
GO

DROP PROCEDURE IF EXISTS babel_4529_types
GO

DROP PROCEDURE IF EXISTS babel_4529_sp_sproc_columns_view
GO

DROP PROCEDURE IF EXISTS babel_4529_systypes
GO
