DROP PROCEDURE IF EXISTS get_column_info_p1;
GO

DROP TABLE IF EXISTS TestMoneyTable;
GO

DROP TABLE IF EXISTS ResultTable1;
GO

DROP TABLE IF EXISTS ResultTable2;
GO

DROP TABLE IF EXISTS ResultTable3;
GO

DROP TABLE IF EXISTS ResultTable4;
GO

DROP TABLE IF EXISTS ResultTable5;
GO

DROP TABLE IF EXISTS ResultTable6;
GO

DROP TABLE IF EXISTS ResultTable7;
GO

DROP TABLE IF EXISTS ResultTable8;
GO

DROP TABLE IF EXISTS ResultTable9;
GO

DROP TABLE IF EXISTS ResultTable10;
GO

DROP TABLE IF EXISTS EmptyMoneyTable;
GO

DROP TABLE IF EXISTS ResultTableEmpty;
GO

DROP TABLE IF EXISTS ExtremeMoneyTable;
GO

DROP TABLE IF EXISTS ResultTableExtreme;
GO

DROP TABLE IF EXISTS MixedNullMoneyTable;
GO

DROP TABLE IF EXISTS ResultTableMixedNull;
GO

DROP TABLE IF EXISTS OverflowMoneyTable;
GO

DROP TABLE IF EXISTS ResultTableOverflow;
GO

DROP TABLE IF EXISTS NonMoneyTable;
GO

DROP TABLE IF EXISTS ResultTableNonMoney;
GO
