USE master
go

DROP DATABASE sys_identity_columns_dep_vu_prepare_db1
DROP PROCEDURE sys_identity_columns_dep_vu_prepare_p1
DROP FUNCTION sys_identity_columns_dep_vu_prepare_f1
DROP TABLE sys_identity_columns_dep_vu_prepare
go
