DROP PROCEDURE sys_all_parameters_vu_prepare_addTwo
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_complexProc
GO

DROP PROCEDURE sys_all_parameters_schema_vu_prepare.sys_all_parameters_vu_prepare_complexProc
GO

DROP SCHEMA sys_all_parameters_schema_vu_prepare
GO

DROP FUNCTION sys_all_parameters_vu_prepare_scalFunc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_tableFunc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_InlineTableFunc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_tableFunc2
GO

DROP FUNCTION sys_all_parameters_vu_prepare_InlineTableFunc2
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_tvpProc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_myDecFunc
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_typeModifier
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_DataTypeExamples
GO

DROP TYPE sys_all_parameters_vu_prepare_myDec
GO

DROP TYPE sys_all_parameters_vu_prepare_myTableParam
GO
