DROP DATABASE sys_babelfish_sysdatabases_vu_prepare_db
GO

DROP VIEW sys_babelfish_sysdatabases_vu_prepare_view
GO

DROP PROC sys_babelfish_sysdatabases_vu_prepare_proc
GO

DROP FUNCTION sys_babelfish_sysdatabases_vu_prepare_func
GO
