CREATE PROCEDURE p1_tv_nocomma
AS 
BEGIN                           
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL PRIMARY KEY(a))
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(1,3) 
END
go
CREATE PROCEDURE p2_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL PRIMARY KEY(a,b))
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(1,2) 
END
go
CREATE PROCEDURE p3_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL PRIMARY KEY(a))
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(1,3) 
END
go
CREATE PROCEDURE p4_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL UNIQUE(a,b))
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(1,2) 
END
go
CREATE PROCEDURE p5_tv_nocomma
AS 
BEGIN                       
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL PRIMARY KEY)
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(2,2) 
END
go
CREATE PROCEDURE p6_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL PRIMARY KEY, b INT NOT NULL)
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(1,3) 
END
go
CREATE PROCEDURE p7_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL UNIQUE)
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(2,2) 
END
go
CREATE PROCEDURE p8_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL UNIQUE, b INT NOT NULL)
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(1,3) 
END
go
CREATE PROCEDURE p9_tv_nocomma
AS 
BEGIN
	DECLARE @tv TABLE (a INT NOT NULL, b INT NOT NULL CHECK(a>0))
	INSERT @tv VALUES(1,2) 
	INSERT @tv VALUES(0,3) 
END
go
