DROP VIEW test_conv_string_to_datetime_v1
GO
DROP PROCEDURE test_conv_string_to_datetime_p1
GO
DROP FUNCTION test_conv_string_to_datetime_f1()
GO

DROP VIEW test_conv_string_to_datetime_v2
GO
DROP PROCEDURE test_conv_string_to_datetime_p2
GO
DROP FUNCTION test_conv_string_to_datetime_f2()
GO

DROP VIEW test_conv_string_to_datetime_v3
GO
DROP PROCEDURE test_conv_string_to_datetime_p3
GO
DROP FUNCTION test_conv_string_to_datetime_f3()
GO
