DROP VIEW typeid_typename_dep_vu_prepare_view1
GO

DROP PROC typeid_typename_dep_vu_prepare_proc1
GO

DROP VIEW typeid_typename_dep_vu_prepare_view2
GO

DROP PROC typeid_typename_dep_vu_prepare_proc2
GO

DROP TYPE typeid_typename_dep_vu_prepare_t1
GO

DROP TYPE typeid_typename_dep_vu_prepare_s1.typeid_typename_dep_vu_prepare_t1
GO

DROP SCHEMA typeid_typename_dep_vu_prepare_s1
GO

DROP USER typeid_typename_dep_vu_prepare_user1
GO

DROP LOGIN typeid_typename_dep_vu_prepare_log1
GO

