name: 'Upgrade till final version and run verify tests'

runs: 
  using: "composite"
  steps:
    - name: Print Upgrade Path
      run: echo "Upgrading to final version through intermediate versions ..."
      shell: bash

