/*-------------------------------------------------------------------------
 *
 * pltsql_nodetags.h
 *    Generated node infrastructure code
 *
 * Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by gen_pltsql_node_support.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PLTSQL_NODETAGS_H
#define PLTSQL_NODETAGS_H

/* PLtsql NodeTag start offset — used by is_pltsql_node() checks */
#define PLTSQL_NODETAG_START 10000

/*
 * PLtsql NodeTag values, auto-generated by gen_pltsql_node_support.pl.
 * Offset from 10000 to avoid collision with engine NodeTags.
 */

#define T_PLtsql_type ((NodeTag) (PLTSQL_NODETAG_START + 0))
#define T_PLtsql_expr ((NodeTag) (PLTSQL_NODETAG_START + 1))
#define T_PLtsql_datum ((NodeTag) (PLTSQL_NODETAG_START + 2))
#define T_PLtsql_variable ((NodeTag) (PLTSQL_NODETAG_START + 3))
#define T_PLtsql_var ((NodeTag) (PLTSQL_NODETAG_START + 4))
#define T_PLtsql_row ((NodeTag) (PLTSQL_NODETAG_START + 5))
#define T_PLtsql_rec ((NodeTag) (PLTSQL_NODETAG_START + 6))
#define T_PLtsql_tbl ((NodeTag) (PLTSQL_NODETAG_START + 7))
#define T_PLtsql_recfield ((NodeTag) (PLTSQL_NODETAG_START + 8))
#define T_PLtsql_arrayelem ((NodeTag) (PLTSQL_NODETAG_START + 9))
#define T_PLtsql_nsitem ((NodeTag) (PLTSQL_NODETAG_START + 10))
#define T_PLtsql_stmt ((NodeTag) (PLTSQL_NODETAG_START + 11))
#define T_PLtsql_condition ((NodeTag) (PLTSQL_NODETAG_START + 12))
#define T_PLtsql_exception_block ((NodeTag) (PLTSQL_NODETAG_START + 13))
#define T_PLtsql_exception ((NodeTag) (PLTSQL_NODETAG_START + 14))
#define T_PLtsql_stmt_block ((NodeTag) (PLTSQL_NODETAG_START + 15))
#define T_PLtsql_stmt_assign ((NodeTag) (PLTSQL_NODETAG_START + 16))
#define T_PLtsql_stmt_perform ((NodeTag) (PLTSQL_NODETAG_START + 17))
#define T_PLtsql_stmt_call ((NodeTag) (PLTSQL_NODETAG_START + 18))
#define T_PLtsql_stmt_commit ((NodeTag) (PLTSQL_NODETAG_START + 19))
#define T_PLtsql_stmt_rollback ((NodeTag) (PLTSQL_NODETAG_START + 20))
#define T_PLtsql_stmt_set ((NodeTag) (PLTSQL_NODETAG_START + 21))
#define T_PLtsql_diag_item ((NodeTag) (PLTSQL_NODETAG_START + 22))
#define T_PLtsql_stmt_getdiag ((NodeTag) (PLTSQL_NODETAG_START + 23))
#define T_PLtsql_stmt_if ((NodeTag) (PLTSQL_NODETAG_START + 24))
#define T_PLtsql_if_elsif ((NodeTag) (PLTSQL_NODETAG_START + 25))
#define T_PLtsql_stmt_case ((NodeTag) (PLTSQL_NODETAG_START + 26))
#define T_PLtsql_case_when ((NodeTag) (PLTSQL_NODETAG_START + 27))
#define T_PLtsql_stmt_loop ((NodeTag) (PLTSQL_NODETAG_START + 28))
#define T_PLtsql_stmt_while ((NodeTag) (PLTSQL_NODETAG_START + 29))
#define T_PLtsql_stmt_fori ((NodeTag) (PLTSQL_NODETAG_START + 30))
#define T_PLtsql_stmt_forq ((NodeTag) (PLTSQL_NODETAG_START + 31))
#define T_PLtsql_stmt_fors ((NodeTag) (PLTSQL_NODETAG_START + 32))
#define T_PLtsql_stmt_forc ((NodeTag) (PLTSQL_NODETAG_START + 33))
#define T_PLtsql_stmt_dynfors ((NodeTag) (PLTSQL_NODETAG_START + 34))
#define T_PLtsql_stmt_foreach_a ((NodeTag) (PLTSQL_NODETAG_START + 35))
#define T_PLtsql_stmt_open ((NodeTag) (PLTSQL_NODETAG_START + 36))
#define T_PLtsql_stmt_fetch ((NodeTag) (PLTSQL_NODETAG_START + 37))
#define T_PLtsql_stmt_close ((NodeTag) (PLTSQL_NODETAG_START + 38))
#define T_PLtsql_stmt_exit ((NodeTag) (PLTSQL_NODETAG_START + 39))
#define T_PLtsql_stmt_insert_bulk ((NodeTag) (PLTSQL_NODETAG_START + 40))
#define T_PLtsql_stmt_dbcc ((NodeTag) (PLTSQL_NODETAG_START + 41))
#define T_PLtsql_stmt_return ((NodeTag) (PLTSQL_NODETAG_START + 42))
#define T_PLtsql_stmt_return_next ((NodeTag) (PLTSQL_NODETAG_START + 43))
#define T_PLtsql_stmt_return_query ((NodeTag) (PLTSQL_NODETAG_START + 44))
#define T_PLtsql_stmt_raise ((NodeTag) (PLTSQL_NODETAG_START + 45))
#define T_PLtsql_raise_option ((NodeTag) (PLTSQL_NODETAG_START + 46))
#define T_PLtsql_stmt_grantdb ((NodeTag) (PLTSQL_NODETAG_START + 47))
#define T_PLtsql_stmt_change_dbowner ((NodeTag) (PLTSQL_NODETAG_START + 48))
#define T_PLtsql_stmt_alter_db ((NodeTag) (PLTSQL_NODETAG_START + 49))
#define T_PLtsql_stmt_fulltextindex ((NodeTag) (PLTSQL_NODETAG_START + 50))
#define T_PLtsql_stmt_grantschema ((NodeTag) (PLTSQL_NODETAG_START + 51))
#define T_PLtsql_stmt_partition_function ((NodeTag) (PLTSQL_NODETAG_START + 52))
#define T_PLtsql_stmt_partition_scheme ((NodeTag) (PLTSQL_NODETAG_START + 53))
#define T_PLtsql_stmt_assert ((NodeTag) (PLTSQL_NODETAG_START + 54))
#define T_PLtsql_txn_data ((NodeTag) (PLTSQL_NODETAG_START + 55))
#define T_PLtsql_stmt_execsql ((NodeTag) (PLTSQL_NODETAG_START + 56))
#define T_PLtsql_stmt_set_explain_mode ((NodeTag) (PLTSQL_NODETAG_START + 57))
#define T_PLtsql_stmt_dynexecute ((NodeTag) (PLTSQL_NODETAG_START + 58))
#define T_InlineCodeBlockArgs ((NodeTag) (PLTSQL_NODETAG_START + 59))
#define T_PLtsql_function ((NodeTag) (PLTSQL_NODETAG_START + 60))
#define T_PLtsql_stmt_print ((NodeTag) (PLTSQL_NODETAG_START + 61))
#define T_PLtsql_stmt_kill ((NodeTag) (PLTSQL_NODETAG_START + 62))
#define T_PLtsql_stmt_init ((NodeTag) (PLTSQL_NODETAG_START + 63))
#define T_PLtsql_stmt_try_catch ((NodeTag) (PLTSQL_NODETAG_START + 64))
#define T_PLtsql_stmt_query_set ((NodeTag) (PLTSQL_NODETAG_START + 65))
#define T_PLtsql_stmt_push_result ((NodeTag) (PLTSQL_NODETAG_START + 66))
#define T_PLtsql_stmt_exec ((NodeTag) (PLTSQL_NODETAG_START + 67))
#define T_tsql_exec_param ((NodeTag) (PLTSQL_NODETAG_START + 68))
#define T_PLtsql_stmt_exec_sp ((NodeTag) (PLTSQL_NODETAG_START + 69))
#define T_PLtsql_stmt_decl_table ((NodeTag) (PLTSQL_NODETAG_START + 70))
#define T_PLtsql_stmt_exec_batch ((NodeTag) (PLTSQL_NODETAG_START + 71))
#define T_PLtsql_stmt_raiserror ((NodeTag) (PLTSQL_NODETAG_START + 72))
#define T_PLtsql_stmt_throw ((NodeTag) (PLTSQL_NODETAG_START + 73))
#define T_PLtsql_stmt_deallocate ((NodeTag) (PLTSQL_NODETAG_START + 74))
#define T_PLtsql_stmt_decl_cursor ((NodeTag) (PLTSQL_NODETAG_START + 75))
#define T_PLtsql_stmt_goto ((NodeTag) (PLTSQL_NODETAG_START + 76))
#define T_PLtsql_stmt_label ((NodeTag) (PLTSQL_NODETAG_START + 77))
#define T_PLtsql_stmt_usedb ((NodeTag) (PLTSQL_NODETAG_START + 78))
#define T_PLtsql_stmt_save_ctx ((NodeTag) (PLTSQL_NODETAG_START + 79))
#define T_PLtsql_stmt_restore_ctx_full ((NodeTag) (PLTSQL_NODETAG_START + 80))
#define T_PLtsql_stmt_restore_ctx_partial ((NodeTag) (PLTSQL_NODETAG_START + 81))

#endif /* PLTSQL_NODETAGS_H */
