DROP TABLE sys_check_constraints_vu_prepare
GO

DROP PROC sys_check_constraints_vu_prepare_proc
GO

DROP FUNCTION sys_check_constraints_vu_prepare_func
GO

DROP VIEW sys_check_constraints_vu_prepare_view
GO

DROP TABLE IF EXISTS sys_check_constraints_vu_prepare_t1
GO
