DROP PROCEDURE sys_all_parameters_vu_prepare_addTwo
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_complexProc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_scalFunc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_tableFunc
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_tvpProc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_myDecFunc
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_typeModifier
GO

DROP PROCEDURE sys_all_parameters_vu_prepare_DataTypeExamples
GO

DROP TYPE sys_all_parameters_vu_prepare_myDec
GO

DROP TYPE sys_all_parameters_vu_prepare_myTableParam
GO

DROP VIEW sys_all_parameters_vu_prepare_upgrade_view
GO

DROP PROC sys_all_parameters_vu_prepare_upgrade_proc
GO

DROP FUNCTION sys_all_parameters_vu_prepare_upgrade_func
GO
