DROP VIEW sys_all_parameters_dep_vu_prepare_upgrade_view
GO

DROP PROC sys_all_parameters_dep_vu_prepare_upgrade_proc
GO

DROP FUNCTION sys_all_parameters_dep_vu_prepare_upgrade_func
GO

DROP PROC sys_all_parameters_dep_vu_prepare_addTwo
GO
