USE sys_events_vu_prepare_database1
GO

DROP TRIGGER sys_events_vu_prepare_trig3
GO
DROP TABLE sys_events_vu_prepare_table1
GO

USE master
GO
DROP DATABASE sys_events_vu_prepare_database1
GO

DROP VIEW sys_events_vu_prepare_view
GO
DROP PROC sys_events_vu_prepare_proc
GO
DROP FUNCTION dbo.sys_events_vu_prepare_func()
GO

DROP TRIGGER sys_events_vu_prepare_trig1
GO
DROP TRIGGER sys_events_vu_prepare_schema1.sys_events_vu_prepare_trig2
GO
DROP TABLE sys_events_vu_prepare_table1
GO
DROP TABLE sys_events_vu_prepare_schema1.sys_events_vu_prepare_table1
GO
DROP SCHEMA sys_events_vu_prepare_schema1
GO