DROP TYPE IF EXISTS test1
GO
DROP TYPE IF EXISTS test2
GO
DROP TYPE IF EXISTS shc_test.test3
GO
DROP TYPE IF EXISTS test4
GO
DROP SCHEMA IF EXISTS shc_test
GO

CREATE TYPE test1 FROM varchar(11) NOT NULL ;
GO

CREATE TYPE test2 FROM int NULL ;
GO

CREATE SCHEMA shc_test
GO

Create type shc_test.test3 FROM varchar(11) NOT NULL ;
GO

Create type test4 from numeric(15,4)
GO

--DROP
DROP TYPE IF EXISTS test1
GO
DROP TYPE IF EXISTS test2
GO
DROP TYPE IF EXISTS shc_test.test3
GO
DROP TYPE IF EXISTS test4
GO
DROP SCHEMA IF EXISTS shc_test
GO
