DROP TABLE sp_xml_preparedocument_HandleStore;
GO

DROP DATABASE sp_xml_preparedocument_temp_db;
GO

DROP TABLE handle_store;
GO

DROP PROCEDURE test_xml_proc;
GO

DROP TYPE IF EXISTS XMLCharType
GO

DROP TYPE IF EXISTS XMLVarcharType
GO

DROP TYPE IF EXISTS XMLNCharType
GO

DROP TYPE IF EXISTS XMLNVarcharType
GO

DROP TYPE IF EXISTS XMLTextType
GO

DROP TYPE IF EXISTS XMLNTextType
GO

DROP PROCEDURE IF EXISTS TestXMLPrepareDocument_Char
GO

DROP PROCEDURE IF EXISTS TestXMLPrepareDocument_Varchar
GO

DROP PROCEDURE IF EXISTS TestXMLPrepareDocument_NChar
GO

DROP PROCEDURE IF EXISTS TestXMLPrepareDocument_NVarchar
GO

DROP PROCEDURE IF EXISTS TestXMLPrepareDocument_Text
GO

DROP PROCEDURE IF EXISTS TestXMLPrepareDocument_NText
GO