name: Babelfish for PostgreSQL Extensions Bug Report
description: File a bug report for Babelfish Extensions
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please provide details about the bug, and the steps needed to recreate the bug.
      placeholder: Tell us about the bug.
      value: "Tell us about the bug."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of Babelfish are you running?
      options:
        - BABEL_1_X_DEV (Default)
    validations:
      required: true
  - type: dropdown
    id: extension
    attributes:
      label: Extension
      description: Which extension is the problem occurring with?
      options:
        - babelfishpg_tsql (Default)
        - babelfishpg_tds
        - babelfishpg_money
        - babelfishpg_common
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Which flavor of Linux are you using when you see the bug?
      multiple: true
      options:
        - Ubuntu (Default)
        - Fedora
        - Amazon Linux
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.github.io/code-of-conduct-faq).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true