name: Babelfish for PostgreSQL Question
description: Ask a question of the Babelfish maintainers
title: "[Question]: "
labels: ["question", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Babelfish.
  - type: textarea
    id: what-question
    attributes:
      label: What's your question?
      description: Tell us about your question in detail.
      placeholder: Provide as much information about your question as possible.
      value: "Tell us about your question."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of Babelfish are you running?
      options:
        - BABEL_3_X_DEV (Default)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or information
      description: Please copy and paste any relevant log output here. The log output will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.github.io/code-of-conduct-faq).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
