DECLARE @id SYS.VARBINARY(85)
SET @id = (SELECT SYS.SUSER_SID())
SELECT SYS.SUSER_SNAME(@id)
GO

DECLARE @id SYS.VARBINARY(85)
SET @id = (SELECT SYS.SUSER_SID('jdbc_user'))
SELECT SYS.SUSER_SNAME(@id)
GO

SELECT SYS.SUSER_SID('non_existent_user')
GO
