DROP VIEW IF EXISTS EOMONTH_EndOfMonthView;
GO

DROP PROCEDURE IF EXISTS GetEndOfMonthDate_EOMONTH;
GO

DROP VIEW IF EXISTS EOMONTH_EndOfNextMonthView;
GO

DROP PROCEDURE IF EXISTS GetEndOfNextMonthDate_EOMONTH;
GO
