DROP VIEW IF EXISTS parsename_EmployeeDatabaseView1_before_14_11_or_15_6;
GO

DROP PROCEDURE IF EXISTS parsename_GetEmployeeDatabaseName1_before_14_11_or_15_6;
GO

DROP VIEW IF EXISTS parsename_EmployeeDatabaseView2_before_14_11_or_15_6;
GO

DROP PROCEDURE IF EXISTS parsename_GetEmployeeDatabaseName2_before_14_11_or_15_6;
GO

DROP VIEW IF EXISTS parsename_EmployeeDatabaseView3_before_14_11_or_15_6;
GO

DROP PROCEDURE IF EXISTS parsename_GetEmployeeDatabaseName3_before_14_11_or_15_6;
GO

DROP TABLE IF EXISTS parsename_Employee_before_14_11_or_15_6;
GO