DROP VIEW test_conv_string_to_smalldatetime_v1
GO
DROP PROCEDURE test_conv_string_to_smalldatetime_p1
GO
DROP FUNCTION test_conv_string_to_smalldatetime_f1()
GO

DROP VIEW test_conv_string_to_smalldatetime_v2
GO
DROP PROCEDURE test_conv_string_to_smalldatetime_p2
GO
DROP FUNCTION test_conv_string_to_smalldatetime_f2()
GO