-- VARBINARY (regular)
CREATE VIEW cast_text_to_varbinary_1 AS
SELECT CAST('-123.456325678543' AS VARBINARY(40))
UNION ALL SELECT TRY_CAST('-123.456325678543' AS VARBINARY(40));
GO
CREATE VIEW conv_text_to_varbinary_1 AS
SELECT CONVERT(VARBINARY(40), '-123.456325678543')
UNION ALL SELECT TRY_CONVERT(VARBINARY(40), '-123.456325678543');
GO

-- VARBINARY (Unicode)
CREATE VIEW cast_text_to_varbinary_2 AS
SELECT CAST(N'😎Bilal DENİZLİ Türkiye' AS VARBINARY(40))
UNION ALL SELECT TRY_CAST(N'😎Bilal DENİZLİ Türkiye' AS VARBINARY(40));
GO
CREATE VIEW conv_text_to_varbinary_2 AS
SELECT CONVERT(VARBINARY(40), N'😎Bilal DENİZLİ Türkiye')
UNION ALL SELECT TRY_CONVERT(VARBINARY(40), N'😎Bilal DENİZLİ Türkiye');
GO

-- BINARY (regular)
CREATE VIEW cast_text_to_binary_1 AS
SELECT CAST('-123.456325678543' AS BINARY(40))
UNION ALL SELECT TRY_CAST('-123.456325678543' AS BINARY(40));
GO
CREATE VIEW conv_text_to_binary_1 AS
SELECT CONVERT(BINARY(40), '-123.456325678543')
UNION ALL SELECT TRY_CONVERT(BINARY(40), '-123.456325678543');
GO

-- BINARY (Unicode)
CREATE VIEW cast_text_to_binary_2 AS
SELECT CAST(N'😎Bilal DENİZLİ Türkiye' AS BINARY(40))
UNION ALL SELECT TRY_CAST(N'😎Bilal DENİZLİ Türkiye' AS BINARY(40));
GO
CREATE VIEW conv_text_to_binary_2 AS
SELECT CONVERT(BINARY(40), N'😎Bilal DENİZLİ Türkiye')
UNION ALL SELECT TRY_CONVERT(BINARY(40), N'😎Bilal DENİZLİ Türkiye');
GO

-- VARBINARY
CREATE PROCEDURE p_text_to_varbinary_reg
AS
BEGIN
  SELECT CAST('-123.456325678543' AS VARBINARY(40)) AS val
  UNION ALL SELECT TRY_CAST('-123.456325678543' AS VARBINARY(40));

  SELECT CONVERT(VARBINARY(40), '-123.456325678543') AS val
  UNION ALL SELECT TRY_CONVERT(VARBINARY(40), '-123.456325678543');
END;
GO

CREATE PROCEDURE p_text_to_varbinary_uni
AS
BEGIN
  SELECT CAST(N'😎Bilal DENİZLİ Türkiye' AS VARBINARY(40)) AS val
  UNION ALL SELECT TRY_CAST(N'😎Bilal DENİZLİ Türkiye' AS VARBINARY(40));

  SELECT CONVERT(VARBINARY(40), N'😎Bilal DENİZLİ Türkiye') AS val
  UNION ALL SELECT TRY_CONVERT(VARBINARY(40), N'😎Bilal DENİZLİ Türkiye');
END;
GO

-- BINARY
CREATE PROCEDURE p_text_to_binary_reg
AS
BEGIN
  SELECT CAST('-123.456325678543' AS BINARY(40)) AS val
  UNION ALL SELECT TRY_CAST('-123.456325678543' AS BINARY(40));

  SELECT CONVERT(BINARY(40), '-123.456325678543') AS val
  UNION ALL SELECT TRY_CONVERT(BINARY(40), '-123.456325678543');
END;
GO

CREATE PROCEDURE p_text_to_binary_uni
AS
BEGIN
  SELECT CAST(N'😎Bilal DENİZLİ Türkiye' AS BINARY(40)) AS val
  UNION ALL SELECT TRY_CAST(N'😎Bilal DENİZLİ Türkiye' AS BINARY(40));

  SELECT CONVERT(BINARY(40), N'😎Bilal DENİZLİ Türkiye') AS val
  UNION ALL SELECT TRY_CONVERT(BINARY(40), N'😎Bilal DENİZLİ Türkiye');
END;
GO

-- VARBINARY
GO
CREATE FUNCTION f_text_to_varbinary_reg()
RETURNS @t TABLE (val VARBINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST('-123.456325678543' AS VARBINARY(40));
  INSERT INTO @t SELECT TRY_CAST('-123.456325678543' AS VARBINARY(40));
  INSERT INTO @t SELECT CONVERT(VARBINARY(40), '-123.456325678543');
  INSERT INTO @t SELECT TRY_CONVERT(VARBINARY(40), '-123.456325678543');
  RETURN;
END;
GO

GO
CREATE FUNCTION f_text_to_varbinary_uni()
RETURNS @t TABLE (val VARBINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST(N'😎Bilal DENİZLİ Türkiye' AS VARBINARY(40));
  INSERT INTO @t SELECT TRY_CAST(N'😎Bilal DENİZLİ Türkiye' AS VARBINARY(40));
  INSERT INTO @t SELECT CONVERT(VARBINARY(40), N'😎Bilal DENİZLİ Türkiye');
  INSERT INTO @t SELECT TRY_CONVERT(VARBINARY(40), N'😎Bilal DENİZLİ Türkiye');
  RETURN;
END;
GO

-- BINARY
GO
CREATE FUNCTION f_text_to_binary_reg()
RETURNS @t TABLE (val BINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST('-123.456325678543' AS BINARY(40));
  INSERT INTO @t SELECT TRY_CAST('-123.456325678543' AS BINARY(40));
  INSERT INTO @t SELECT CONVERT(BINARY(40), '-123.456325678543');
  INSERT INTO @t SELECT TRY_CONVERT(BINARY(40), '-123.456325678543');
  RETURN;
END;
GO

GO
CREATE FUNCTION f_text_to_binary_uni()
RETURNS @t TABLE (val BINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST(N'😎Bilal DENİZLİ Türkiye' AS BINARY(40));
  INSERT INTO @t SELECT TRY_CAST(N'😎Bilal DENİZLİ Türkiye' AS BINARY(40));
  INSERT INTO @t SELECT CONVERT(BINARY(40), N'😎Bilal DENİZLİ Türkiye');
  INSERT INTO @t SELECT TRY_CONVERT(BINARY(40), N'😎Bilal DENİZLİ Türkiye');
  RETURN;
END;
GO

-- VARBINARY (regular)
CREATE VIEW cast_text_to_varbinary_hw_1 AS
SELECT CAST('Hello World!' AS VARBINARY(40))
UNION ALL SELECT TRY_CAST('Hello World!' AS VARBINARY(40));
GO
CREATE VIEW conv_text_to_varbinary_hw_1 AS
SELECT CONVERT(VARBINARY(40), 'Hello World!')
UNION ALL SELECT TRY_CONVERT(VARBINARY(40), 'Hello World!');
GO

-- VARBINARY (Unicode)
CREATE VIEW cast_text_to_varbinary_hw_2 AS
SELECT CAST(N'Hello World!' AS VARBINARY(40))
UNION ALL SELECT TRY_CAST(N'Hello World!' AS VARBINARY(40));
GO
CREATE VIEW conv_text_to_varbinary_hw_2 AS
SELECT CONVERT(VARBINARY(40), N'Hello World!')
UNION ALL SELECT TRY_CONVERT(VARBINARY(40), N'Hello World!');
GO

-- BINARY (regular)
CREATE VIEW cast_text_to_binary_hw_1 AS
SELECT CAST('Hello World!' AS BINARY(40))
UNION ALL SELECT TRY_CAST('Hello World!' AS BINARY(40));
GO
CREATE VIEW conv_text_to_binary_hw_1 AS
SELECT CONVERT(BINARY(40), 'Hello World!')
UNION ALL SELECT TRY_CONVERT(BINARY(40), 'Hello World!');
GO

-- BINARY (Unicode)
CREATE VIEW cast_text_to_binary_hw_2 AS
SELECT CAST(N'Hello World!' AS BINARY(40))
UNION ALL SELECT TRY_CAST(N'Hello World!' AS BINARY(40));
GO
CREATE VIEW conv_text_to_binary_hw_2 AS
SELECT CONVERT(BINARY(40), N'Hello World!')
UNION ALL SELECT TRY_CONVERT(BINARY(40), N'Hello World!');
GO

-- VARBINARY
CREATE PROCEDURE p_text_to_varbinary_reg_hw
AS
BEGIN
  SELECT CAST('Hello World!' AS VARBINARY(40)) AS val
  UNION ALL SELECT TRY_CAST('Hello World!' AS VARBINARY(40));

  SELECT CONVERT(VARBINARY(40), 'Hello World!') AS val
  UNION ALL SELECT TRY_CONVERT(VARBINARY(40), 'Hello World!');
END;
GO

CREATE PROCEDURE p_text_to_varbinary_uni_hw
AS
BEGIN
  SELECT CAST(N'Hello World!' AS VARBINARY(40)) AS val
  UNION ALL SELECT TRY_CAST(N'Hello World!' AS VARBINARY(40));

  SELECT CONVERT(VARBINARY(40), N'Hello World!') AS val
  UNION ALL SELECT TRY_CONVERT(VARBINARY(40), N'Hello World!');
END;
GO

-- BINARY
CREATE PROCEDURE p_text_to_binary_reg_hw
AS
BEGIN
  SELECT CAST('Hello World!' AS BINARY(40)) AS val
  UNION ALL SELECT TRY_CAST('Hello World!' AS BINARY(40));

  SELECT CONVERT(BINARY(40), 'Hello World!') AS val
  UNION ALL SELECT TRY_CONVERT(BINARY(40), 'Hello World!');
END;
GO

CREATE PROCEDURE p_text_to_binary_uni_hw
AS
BEGIN
  SELECT CAST(N'Hello World!' AS BINARY(40)) AS val
  UNION ALL SELECT TRY_CAST(N'Hello World!' AS BINARY(40));

  SELECT CONVERT(BINARY(40), N'Hello World!') AS val
  UNION ALL SELECT TRY_CONVERT(BINARY(40), N'Hello World!');
END;
GO

-- VARBINARY
CREATE FUNCTION dbo.f_text_to_varbinary_reg_hw()
RETURNS @t TABLE (val VARBINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST('Hello World!' AS VARBINARY(40));
  INSERT INTO @t SELECT TRY_CAST('Hello World!' AS VARBINARY(40));
  INSERT INTO @t SELECT CONVERT(VARBINARY(40), 'Hello World!');
  INSERT INTO @t SELECT TRY_CONVERT(VARBINARY(40), 'Hello World!');
  RETURN;
END;
GO

CREATE FUNCTION dbo.f_text_to_varbinary_uni_hw()
RETURNS @t TABLE (val VARBINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST(N'Hello World!' AS VARBINARY(40));
  INSERT INTO @t SELECT TRY_CAST(N'Hello World!' AS VARBINARY(40));
  INSERT INTO @t SELECT CONVERT(VARBINARY(40), N'Hello World!');
  INSERT INTO @t SELECT TRY_CONVERT(VARBINARY(40), N'Hello World!');
  RETURN;
END;
GO

-- BINARY
CREATE FUNCTION dbo.f_text_to_binary_reg_hw()
RETURNS @t TABLE (val BINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST('Hello World!' AS BINARY(40));
  INSERT INTO @t SELECT TRY_CAST('Hello World!' AS BINARY(40));
  INSERT INTO @t SELECT CONVERT(BINARY(40), 'Hello World!');
  INSERT INTO @t SELECT TRY_CONVERT(BINARY(40), 'Hello World!');
  RETURN;
END;
GO

CREATE FUNCTION dbo.f_text_to_binary_uni_hw()
RETURNS @t TABLE (val BINARY(40))
AS
BEGIN
  INSERT INTO @t SELECT CAST(N'Hello World!' AS BINARY(40));
  INSERT INTO @t SELECT TRY_CAST(N'Hello World!' AS BINARY(40));
  INSERT INTO @t SELECT CONVERT(BINARY(40), N'Hello World!');
  INSERT INTO @t SELECT TRY_CONVERT(BINARY(40), N'Hello World!');
  RETURN;
END;
GO
