DROP TABLE IF EXISTS UdtTable
GO
DROP TYPE IF EXISTS UDT_TIME
GO
DROP TYPE IF EXISTS UDT_DATE
GO
DROP TYPE IF EXISTS UDT_DATETIME
GO
DROP TYPE IF EXISTS UDT_DATETIME2
GO
DROP TYPE IF EXISTS UDT_TIMESTAMP
GO
DROP TYPE IF EXISTS UDT_SMALLDATETIME
GO
DROP TYPE IF EXISTS UDT_DATETIMEOFFSET
GO
