CREATE FUNCTION babel_726_f1(@a smallint, @b bit)
RETURNS BIT AS
BEGIN
    DECLARE @ans BIT
    SELECT @ans = COALESCE(@b, @a)
    RETURN @ans
END
GO

CREATE VIEW babel_726_v1 AS SELECT COALESCE(CAST(1 as BIT), CAST(5 as SMALLINT))
GO

CREATE PROCEDURE babel_726_p1 AS SELECT COALESCE(CAST(1 as BIT), CAST(5 as SMALLINT))
GO

SELECT babel_726_f1(6,0)
GO

SELECT * FROM babel_726_v1
GO

EXEC babel_726_p1
GO
