-- drop views
DROP VIEW binary_datatype_operators_less_than_view
GO

DROP VIEW binary_datatype_operators_less_than_equal_view
GO

DROP VIEW binary_datatype_operators_greater_than_view
GO

DROP VIEW binary_datatype_operators_greater_than_equal_view
GO

DROP VIEW binary_datatype_operators_equal_view
GO

DROP VIEW binary_datatype_operators_not_equal_view
GO
-- drop procedure
DROP PROCEDURE binary_datatype_operators_less_than_proc
GO

DROP PROCEDURE binary_datatype_operators_less_than_equal_proc
GO

DROP PROCEDURE binary_datatype_operators_greater_than_proc
GO

DROP PROCEDURE binary_datatype_operators_greater_than_equal_proc
GO

DROP PROCEDURE binary_datatype_operators_equal_proc
GO

DROP PROCEDURE binary_datatype_operators_not_equal_proc
GO
-- drop function
DROP FUNCTION binary_datatype_operators_less_than_func
GO

DROP FUNCTION binary_datatype_operators_less_than_equal_func
GO

DROP FUNCTION binary_datatype_operators_greater_than_func
GO

DROP FUNCTION binary_datatype_operators_greater_than_equal_func
GO

DROP FUNCTION binary_datatype_operators_equal_func
GO

DROP FUNCTION binary_datatype_operators_not_equal_func
GO
-- drop table
DROP TABLE binary_datatype_operators_test_table
GO