-- ======== REAL
SELECT CAST('NaN' AS REAL);
GO
SELECT CAST('Infinity' AS REAL);
GO
SELECT CAST('+Infinity' AS REAL);
GO
SELECT CAST('-Infinity' AS REAL);
GO
SELECT CAST('inf' AS REAL);
GO
SELECT CAST('+inf' AS REAL);
GO
SELECT CAST('-inf' AS REAL);
GO
SELECT CAST('' AS REAL);
GO
SELECT CAST(' ' AS REAL);
GO

SELECT TRY_CAST('NaN' AS REAL);
GO
SELECT TRY_CAST('Infinity' AS REAL);
GO
SELECT TRY_CAST('+Infinity' AS REAL);
GO
SELECT TRY_CAST('-Infinity' AS REAL);
GO
SELECT TRY_CAST('inf' AS REAL);
GO
SELECT TRY_CAST('+inf' AS REAL);
GO
SELECT TRY_CAST('-inf' AS REAL);
GO
SELECT TRY_CAST('' AS REAL);
GO
SELECT TRY_CAST(' ' AS REAL);
GO

SELECT CONVERT(REAL, 'NaN');
GO
SELECT CONVERT(REAL, 'Infinity');
GO
SELECT CONVERT(REAL, '+Infinity');
GO
SELECT CONVERT(REAL, '-Infinity');
GO
SELECT CONVERT(REAL,'inf');
GO
SELECT CONVERT(REAL, '+inf');
GO
SELECT CONVERT(REAL, '-inf');
GO
SELECT CONVERT(REAL, '');
GO
SELECT CONVERT(REAL, ' ');
GO

SELECT TRY_CONVERT(REAL, 'NaN');
GO
SELECT TRY_CONVERT(REAL, 'Infinity');
GO
SELECT TRY_CONVERT(REAL, '+Infinity');
GO
SELECT TRY_CONVERT(REAL, '-Infinity');
GO
SELECT TRY_CONVERT(REAL,'inf');
GO
SELECT TRY_CONVERT(REAL, '+inf');
GO
SELECT TRY_CONVERT(REAL, '-inf');
GO
SELECT TRY_CONVERT(REAL, '');
GO
SELECT TRY_CONVERT(REAL, ' ');
GO

DECLARE @f REAL='NaN';
SELECT @f;
GO
DECLARE @f REAL='Infinity';
SELECT @f;
GO
DECLARE @f REAL='+Infinity';
SELECT @f;
GO
DECLARE @f REAL='-Infinity';
SELECT @f;
GO
DECLARE @f REAL='inf';
SELECT @f;
GO
DECLARE @f REAL='+inf';
SELECT @f;
GO
DECLARE @f REAL='-inf';
SELECT @f;
GO
DECLARE @f REAL='';
SELECT @f;
GO
DECLARE @f REAL=' ';
SELECT @f;
GO

-- ======== FLOAT
SELECT CAST(N'NaN' AS FLOAT(53));
GO
SELECT CAST(N'Infinity' AS FLOAT);
GO
SELECT CAST(N'+Infinity' AS FLOAT(53));
GO
SELECT CAST(N'-Infinity' AS FLOAT);
GO
SELECT CAST(N'inf' AS FLOAT(53));
GO
SELECT CAST(N'+inf' AS FLOAT);
GO
SELECT CAST(N'-inf' AS FLOAT(53));
GO
SELECT CAST(N'' AS FLOAT);
GO
SELECT CAST(N' ' AS FLOAT(53));
GO

SELECT TRY_CAST(N'NaN' AS FLOAT);
GO
SELECT TRY_CAST(N'Infinity' AS FLOAT(53));
GO
SELECT TRY_CAST(N'+Infinity' AS FLOAT);
GO
SELECT TRY_CAST(N'-Infinity' AS FLOAT(53));
GO
SELECT TRY_CAST(N'inf' AS FLOAT);
GO
SELECT TRY_CAST(N'+inf' AS FLOAT(53));
GO
SELECT TRY_CAST(N'-inf' AS FLOAT);
GO
SELECT TRY_CAST(N'' AS FLOAT(53));
GO
SELECT TRY_CAST(N' ' AS FLOAT);
GO

SELECT CONVERT(FLOAT(53), N'NaN');
GO
SELECT CONVERT(FLOAT, N'Infinity');
GO
SELECT CONVERT(FLOAT(53), N'+Infinity');
GO
SELECT CONVERT(FLOAT, N'-Infinity');
GO
SELECT CONVERT(FLOAT(53),N'inf');
GO
SELECT CONVERT(FLOAT, N'+inf');
GO
SELECT CONVERT(FLOAT(53), N'-inf');
GO
SELECT CONVERT(FLOAT, N'');
GO
SELECT CONVERT(FLOAT(53), N' ');
GO

SELECT TRY_CONVERT(FLOAT, N'NaN');
GO
SELECT TRY_CONVERT(FLOAT(53), N'Infinity');
GO
SELECT TRY_CONVERT(FLOAT, N'+Infinity');
GO
SELECT TRY_CONVERT(FLOAT(53), N'-Infinity');
GO
SELECT TRY_CONVERT(FLOAT, N'inf');
GO
SELECT TRY_CONVERT(FLOAT(53), N'+inf');
GO
SELECT TRY_CONVERT(FLOAT, N'-inf');
GO
SELECT TRY_CONVERT(FLOAT(53), N'');
GO
SELECT TRY_CONVERT(FLOAT, N' ');
GO

DECLARE @f FLOAT(53)=N'NaN';
SELECT @f;
GO
DECLARE @f FLOAT=N'Infinity';
SELECT @f;
GO
DECLARE @f FLOAT(53)=N'+Infinity';
SELECT @f;
GO
DECLARE @f FLOAT=N'-Infinity';
SELECT @f;
GO
DECLARE @f FLOAT(53)=N'inf';
SELECT @f;
GO
DECLARE @f FLOAT=N'+inf';
SELECT @f;
GO
DECLARE @f FLOAT(53)=N'-inf';
SELECT @f;
GO
DECLARE @f FLOAT=N'';
SELECT @f;
GO
DECLARE @f FLOAT(53)=N' ';
SELECT @f;
GO

-- ======== FLOAT with different precisions
SELECT CAST(N'1.1' AS FLOAT(58));
GO
SELECT CAST(N'' AS FLOAT(56));
GO
SELECT CAST(N'1.1' AS FLOAT(-1));
GO
SELECT CAST(N'1.1' AS FLOAT(0));
GO
SELECT CAST(N'3.1' AS FLOAT);
GO
SELECT CAST(N'9.99909' AS FLOAT(53));
GO
SELECT CAST(N'123.321' AS FLOAT);
GO
SELECT CAST(N'1000.10001' AS FLOAT(53));
GO


SELECT TRY_CAST(N'1.1' AS FLOAT(58));
GO
SELECT TRY_CAST(N'' AS FLOAT(56));
GO
SELECT TRY_CAST(N'1.1' AS FLOAT(-1));
GO
SELECT TRY_CAST(N'1.1' AS FLOAT(0));
GO
SELECT TRY_CAST(N'3.1' AS FLOAT);
GO
SELECT TRY_CAST(N'9.99909' AS FLOAT(53));
GO
SELECT TRY_CAST(N'123.321' AS FLOAT);
GO
SELECT TRY_CAST(N'1000.10001' AS FLOAT(53));
GO

SELECT CAST(CAST(N'1.1' AS TEXT) AS FLOAT(53));
GO
SELECT CAST(CAST(N'' AS NTEXT) AS FLOAT(53));
GO
SELECT CAST(CAST(N'Infinity' AS NTEXT) AS FLOAT(53));
GO
SELECT CAST(CAST(N'+inf' AS TEXT) AS REAL);
GO
SELECT CAST(CAST(N'1.1' AS TEXT) AS REAL);
GO
SELECT CAST(CAST(N'' AS NTEXT) AS REAL);
GO
SELECT CAST(CAST(N'+inf' AS CHAR) AS REAL);
GO
SELECT CAST(CAST(N'1.1' AS CHAR) AS REAL);
GO
SELECT CAST(CAST(N'' AS CHAR) AS REAL);
GO
SELECT CAST(CAST(N'+inf' AS NCHAR) AS REAL);
GO
SELECT CAST(CAST(N'1.1' AS NCHAR) AS REAL);
GO
SELECT CAST(CAST(N'' AS NCHAR) AS REAL);
GO

SELECT TRY_CAST(CAST(N'1.1' AS TEXT) AS FLOAT(53));
GO
SELECT TRY_CAST(CAST(N'' AS NTEXT) AS FLOAT(53));
GO
SELECT TRY_CAST(CAST(N'inf' AS NTEXT) AS FLOAT(53));
GO
SELECT TRY_CAST(CAST(N'NaN' AS TEXT) AS REAL);
GO
SELECT TRY_CAST(CAST(N'1.1' AS TEXT) AS REAL);
GO
SELECT TRY_CAST(CAST(N'' AS NTEXT) AS REAL);
GO
SELECT TRY_CAST(CAST(N'1.1' AS CHAR) AS FLOAT(53));
GO
SELECT TRY_CAST(CAST(N'' AS CHAR) AS FLOAT(53));
GO
SELECT TRY_CAST(CAST(N'inf' AS CHAR) AS FLOAT(53));
GO
SELECT TRY_CAST(CAST(N'NaN' AS NCHAR) AS REAL);
GO
SELECT TRY_CAST(CAST(N'1.1' AS NCHAR) AS REAL);
GO
SELECT TRY_CAST(CAST(N'' AS NCHAR) AS REAL);
GO