-- ======== REAL
SELECT CAST('NaN' AS REAL);
GO
SELECT CAST('Infinity' AS REAL);
GO
SELECT CAST('+Infinity' AS REAL);
GO
SELECT CAST('-Infinity' AS REAL);
GO
SELECT CAST('inf' AS REAL);
GO
SELECT CAST('+inf' AS REAL);
GO
SELECT CAST('-inf' AS REAL);
GO

SELECT TRY_CAST('NaN' AS REAL);
GO
SELECT TRY_CAST('Infinity' AS REAL);
GO
SELECT TRY_CAST('+Infinity' AS REAL);
GO
SELECT TRY_CAST('-Infinity' AS REAL);
GO
SELECT TRY_CAST('inf' AS REAL);
GO
SELECT TRY_CAST('+inf' AS REAL);
GO
SELECT TRY_CAST('-inf' AS REAL);
GO

SELECT CONVERT(REAL, 'NaN');
GO
SELECT CONVERT(REAL, 'Infinity');
GO
SELECT CONVERT(REAL, '+Infinity');
GO
SELECT CONVERT(REAL, '-Infinity');
GO
SELECT CONVERT(REAL,'inf');
GO
SELECT CONVERT(REAL, '+inf');
GO
SELECT CONVERT(REAL, '-inf');
GO

SELECT TRY_CONVERT(REAL, 'NaN');
GO
SELECT TRY_CONVERT(REAL, 'Infinity');
GO
SELECT TRY_CONVERT(REAL, '+Infinity');
GO
SELECT TRY_CONVERT(REAL, '-Infinity');
GO
SELECT TRY_CONVERT(REAL,'inf');
GO
SELECT TRY_CONVERT(REAL, '+inf');
GO
SELECT TRY_CONVERT(REAL, '-inf');
GO

DECLARE @f REAL='NaN';
SELECT @f;
GO
DECLARE @f REAL='Infinity';
SELECT @f;
GO
DECLARE @f REAL='+Infinity';
SELECT @f;
GO
DECLARE @f REAL='-Infinity';
SELECT @f;
GO
DECLARE @f REAL='inf';
SELECT @f;
GO
DECLARE @f REAL='+inf';
SELECT @f;
GO
DECLARE @f REAL='-inf';
SELECT @f;
GO


-- ======== REAL
SELECT CAST(N'NaN' AS REAL);
GO
SELECT CAST(N'Infinity' AS REAL);
GO
SELECT CAST(N'+Infinity' AS REAL);
GO
SELECT CAST(N'-Infinity' AS REAL);
GO
SELECT CAST(N'inf' AS REAL);
GO
SELECT CAST(N'+inf' AS REAL);
GO
SELECT CAST(N'-inf' AS REAL);
GO

SELECT TRY_CAST(N'NaN' AS REAL);
GO
SELECT TRY_CAST(N'Infinity' AS REAL);
GO
SELECT TRY_CAST(N'+Infinity' AS REAL);
GO
SELECT TRY_CAST(N'-Infinity' AS REAL);
GO
SELECT TRY_CAST(N'inf' AS REAL);
GO
SELECT TRY_CAST(N'+inf' AS REAL);
GO
SELECT TRY_CAST(N'-inf' AS REAL);
GO

SELECT CONVERT(REAL, N'NaN');
GO
SELECT CONVERT(REAL, N'Infinity');
GO
SELECT CONVERT(REAL, N'+Infinity');
GO
SELECT CONVERT(REAL, N'-Infinity');
GO
SELECT CONVERT(REAL,N'inf');
GO
SELECT CONVERT(REAL, N'+inf');
GO
SELECT CONVERT(REAL, N'-inf');
GO

SELECT TRY_CONVERT(REAL, N'NaN');
GO
SELECT TRY_CONVERT(REAL, N'Infinity');
GO
SELECT TRY_CONVERT(REAL, N'+Infinity');
GO
SELECT TRY_CONVERT(REAL, N'-Infinity');
GO
SELECT TRY_CONVERT(REAL, N'inf');
GO
SELECT TRY_CONVERT(REAL, N'+inf');
GO
SELECT TRY_CONVERT(REAL, N'-inf');
GO

DECLARE @f REAL=N'NaN';
SELECT @f;
GO
DECLARE @f REAL=N'Infinity';
SELECT @f;
GO
DECLARE @f REAL=N'+Infinity';
SELECT @f;
GO
DECLARE @f REAL=N'-Infinity';
SELECT @f;
GO
DECLARE @f REAL=N'inf';
SELECT @f;
GO
DECLARE @f REAL=N'+inf';
SELECT @f;
GO
DECLARE @f REAL=N'-inf';
SELECT @f;
GO