'13.4':
  engine_branch: BABEL_1_0_STABLE__PG_13_4
  extension_branch: BABEL_1_0_0
'13.5':
  engine_branch: BABEL_1_1_STABLE__PG_13_5
  extension_branch: BABEL_1_1_STABLE
'13.6':
  engine_branch: BABEL_1_2_STABLE__PG_13_6
  extension_branch: BABEL_1_2_STABLE
'13.7':
  engine_branch: BABEL_1_3_STABLE__PG_13_7
  extension_branch: BABEL_1_3_STABLE
'13.8':
  engine_branch: BABEL_1_4_STABLE__PG_13_8
  extension_branch: BABEL_1_4_STABLE
'13.9':
  engine_branch: BABEL_1_5_STABLE__PG_13_9
  extension_branch: BABEL_1_5_STABLE
'14.3':
  engine_branch: BABEL_2_1_STABLE__PG_14_3
  extension_branch: BABEL_2_1_STABLE
'14.5':
  engine_branch: BABEL_2_2_STABLE__PG_14_5
  extension_branch: BABEL_2_2_STABLE
'14.6':
  engine_branch: BABEL_2_3_STABLE__PG_14_6
  extension_branch: BABEL_2_3_STABLE
'14.7':
  engine_branch: BABEL_2_4_STABLE__PG_14_7
  extension_branch: BABEL_2_4_STABLE
'14.8':
  engine_branch: BABEL_2_5_STABLE__PG_14_8
  extension_branch: BABEL_2_5_STABLE
'15.2':
  engine_branch: BABEL_3_1_STABLE__PG_15_2
  extension_branch: BABEL_3_1_STABLE
'source.latest':
  engine_branch: latest
  extension_branch: latest
'target.latest':
  engine_branch: latest
  extension_branch: latest
