'13.4':
  engine_branch: BABEL_1_X_DEV__PG_13_4
  extension_branch: BABEL_1_0_0
'13.5':
  engine_branch: BABEL_1_X_DEV__PG_13_5
  extension_branch: BABEL_1_1_0
'13.6':
  engine_branch: BABEL_1_2_STABLE__PG_13_6
  extension_branch: BABEL_1_2_0
'13.7':
  engine_branch: BABEL_1_3_STABLE__PG_13_7
  extension_branch: BABEL_1_3_0
'14.3':
  engine_branch: BABEL_2_1_STABLE__PG_14_3
  extension_branch: BABEL_2_1_STABLE
'14.5':
  engine_branch: BABEL_2_2_STABLE__PG_14_5
  extension_branch: BABEL_2_2_STABLE
'source.latest':
  engine_branch: latest
  extension_branch: latest
'target.latest':
  engine_branch: latest
  extension_branch: latest
