'13.4':
  engine_branch: BABEL_1_0_STABLE__PG_13_4
  extension_branch: BABEL_1_0_0
'13.5':
  engine_branch: BABEL_1_1_STABLE__PG_13_5
  extension_branch: BABEL_1_1_STABLE
'13.6':
  engine_branch: BABEL_1_2_STABLE__PG_13_6
  extension_branch: BABEL_1_2_STABLE
'13.7':
  engine_branch: BABEL_1_3_STABLE__PG_13_7
  extension_branch: BABEL_1_3_STABLE
'13.8':
  engine_branch: BABEL_1_4_STABLE__PG_13_8
  extension_branch: BABEL_1_4_STABLE
'13.9':
  engine_branch: BABEL_1_5_STABLE__PG_13_9
  extension_branch: BABEL_1_5_STABLE
'14.3':
  engine_branch: BABEL_2_1_STABLE__PG_14_3
  extension_branch: BABEL_2_1_STABLE
'14.5':
  engine_branch: BABEL_2_2_STABLE__PG_14_5
  extension_branch: BABEL_2_2_STABLE
'14.6':
  engine_branch: BABEL_2_3_STABLE__PG_14_6
  extension_branch: BABEL_2_3_STABLE
'14.8':
  engine_branch: BABEL_2_5_STABLE__PG_14_8
  extension_branch: BABEL_2_5_STABLE
'14.9':
  engine_branch: BABEL_2_6_STABLE__PG_14_9
  extension_branch: BABEL_2_6_STABLE
'14.10':
  engine_branch: BABEL_2_7_STABLE__PG_14_10
  extension_branch: BABEL_2_7_STABLE
'14.11':
  engine_branch: BABEL_2_8_STABLE__PG_14_11
  extension_branch: BABEL_2_8_STABLE
'14.12':
  engine_branch: BABEL_2_9_STABLE__PG_14_12
  extension_branch: BABEL_2_9_STABLE
'14.13':
  engine_branch: BABEL_2_10_STABLE__PG_14_13
  extension_branch: BABEL_2_10_STABLE
'source.latest':
  engine_branch: latest
  extension_branch: latest
'target.latest':
  engine_branch: latest
  extension_branch: latest
