DROP FUNCTION babel_3409_concat_dep_func1
GO

DROP FUNCTION babel_3409_concat_itvf_func1
GO

DROP VIEW babel_3409_concat_dep_view2
GO

DROP PROCEDURE babel_3409_concat_dep_proc2
GO

DROP FUNCTION babel_3409_concat_dep_func2
GO

DROP FUNCTION babel_3409_concat_itvf_func2
GO

DROP PROCEDURE babel_3409_concat_dep_proc1
GO

DROP VIEW babel_3409_concat_dep_view1
GO

DROP TABLE babel_3409_concat_t2
GO

DROP TABLE babel_3409_concat_t1
GO

DROP TYPE dbo.babel_3409_concat_imageUDT
GO

DROP TYPE dbo.babel_3409_concat_varUDT
GO

DROP PROCEDURE babel_3409_cast_time_to_varchar_proc
GO

DROP FUNCTION babel_3409_cast_time_to_varchar_func
GO

DROP PROCEDURE babel_3409_cast_time_to_nvarchar_proc
GO

DROP FUNCTION babel_3409_cast_time_to_nvarchar_func
GO

DROP PROCEDURE babel_3409_cast_date_to_varchar_proc
GO

DROP FUNCTION babel_3409_cast_date_to_varchar_func
GO

DROP PROCEDURE babel_3409_cast_date_to_nvarchar_proc
GO

DROP FUNCTION babel_3409_cast_date_to_nvarchar_func
GO

DROP PROCEDURE babel_3409_cast_datetimeoffset_to_varchar_proc
GO

DROP FUNCTION babel_3409_cast_datetimeoffset_to_varchar_func
GO

DROP PROCEDURE babel_3409_cast_datetimeoffset_to_nvarchar_proc
GO

DROP FUNCTION babel_3409_cast_datetimeoffset_to_nvarchar_func
GO
