name: 'Build Modified Postgres'

runs:
  using: "composite"
  steps:
    - name: Checkout, Build, and Install the Modified PostgreSQL Instance and Run Tests
      run: |
        cd ..
        git clone https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git
        cd postgresql_modified_for_babelfish
        ./configure --prefix=$HOME/postgres/ --with-python PYTHON=/usr/bin/python2.7 --enable-debug CFLAGS="-ggdb" --with-libxml --with-uuid=ossp --with-icu
        make -j 4 2>error.txt
        make install
        make check
        cd contrib && make && sudo make install
      shell: bash
