name: 'Run ODBC Tests'
description: 'Install and Run Babel ODBC test framework'

runs:
  using: "composite"
  steps:
    - name: Install SQL Server ODBC Driver
      id: install-sql-server-odbc-driver
      run: |
        cd ~
        sudo apt-get install msodbcsql17
      shell: bash
      
    - name: Install unixODBC Driver
      id: install-unix-odbc-driver
      if: always() && steps.install-sql-server-odbc-driver.outcome == 'success'
      run: |
        cd ~
        wget http://www.unixodbc.org/unixODBC-2.3.11.tar.gz
        gunzip unixODBC*.tar.gz
        tar xvf unixODBC*.tar
        cd unixODBC-2.3.11
        ./configure
        make
        sudo make install
      shell: bash

    - name: Install psqlODBC Driver
      id: install-psql-odbc-driver
      if: always() && steps.install-unix-odbc-driver.outcome=='success'
      run: |
        cd ~
        wget https://ftp.postgresql.org/pub/odbc/versions/src/psqlodbc-16.00.0000.tar.gz
        tar -zxvf psqlodbc-16.00.0000.tar.gz
        cd psqlodbc-16.00.0000
        ./configure
        sudo make
        sudo make install
        echo '[ODBC_Driver_16_for_PostgreSQL]' | sudo tee -a /etc/odbcinst.ini > /dev/null
        echo 'Description=ODBC Driver 16 for PostgreSQL Server' | sudo tee -a /etc/odbcinst.ini > /dev/null
        echo 'Driver=/usr/local/lib/psqlodbcw.so' | sudo tee -a /etc/odbcinst.ini > /dev/null
        echo 'UsageCount=1' | sudo tee -a /etc/odbcinst.ini > /dev/null
      shell: bash
    
    - name: Run ODBC Tests
      if: always() && steps.install-sql-server-odbc-driver.outcome == 'success' && steps.install-psql-odbc-driver.outcome == 'success'
      run: |
        cd test/odbc
        cmake -S . -B build
        cmake --build build
        MSSQL_ODBC_DRIVER_NAME="ODBC Driver 17 for SQL Server" \
          MSSQL_BABEL_DB_SERVER=localhost \
          MSSQL_BABEL_DB_PORT=1433 \
          MSSQL_BABEL_DB_USER=jdbc_user \
          MSSQL_BABEL_DB_PASSWORD=12345678 \
          MSSQL_BABEL_DB_NAME=master \
          PSQL_ODBC_DRIVER_NAME=ODBC_Driver_16_for_PostgreSQL \
          PSQL_BABEL_DB_SERVER=localhost \
          PSQL_BABEL_DB_PORT=5432 \
          PSQL_BABEL_DB_USER=jdbc_user \
          PSQL_BABEL_DB_PASSWORD=12345678 \
          PSQL_BABEL_DB_NAME=jdbc_testdb \
          ./build/main
      shell: bash
