name: 'Setup Base Version and Run Tests'
inputs:
  engine_branch: 
    description: "Engine Branch"
    required: true
  extension_branch: 
    description: "Extension Branch"
    required: true
  install_dir:
    description: "Install base version in this directory"
    required: true
  migration_mode:
    description: "Database migration mode for Babelfish"
    required: true
  server_collation_name:
    description: "Server collation name which need to be set in postgresql.conf"
    required: false
    default: "default"
  dump_restore:
    description: "Whether it is version upgrade or dump/restore"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      id: install-dependencies
      if: always()
      uses: ./.github/composite-actions/install-dependencies

    - name: Clone, build, and run tests for Postgres engine using ${{ inputs.engine_branch }}
      id: build-modified-postgres
      uses: ./.github/composite-actions/build-modified-postgres
      if: always() && steps.install-dependencies.outcome == 'success'
      with:
        engine_branch: ${{ inputs.engine_branch }}
        install_dir: ${{ inputs.install_dir }}

    - name: Compile ANTLR
      id: compile-antlr
      if: always() && steps.build-modified-postgres.outcome == 'success'
      uses: ./.github/composite-actions/compile-antlr
      with:
        install_dir: ${{ inputs.install_dir }}

    - name: Set env variables and build extensions
      if: always() && steps.compile-antlr.outcome == 'success'
      uses: ./.github/composite-actions/build-extensions
      with: 
        install_dir: ${{ inputs.install_dir }}
        extension_branch: ${{ inputs.extension_branch }}

    - name: Build tds_fdw Extension
      run: |
        cd ..
        export TDS_FDW_VERSION="2.0.3"
        sudo apt-get install wget
        wget https://github.com/tds-fdw/tds_fdw/archive/v${TDS_FDW_VERSION}.tar.gz
        tar -xvzf v${TDS_FDW_VERSION}.tar.gz
        cd tds_fdw-${TDS_FDW_VERSION}/
        make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config
        sudo make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config install
      shell: bash

    - name: Build vector Extension
      run: |
        cd ..
        export VECTOR_VERSION="0.7.2"
        sudo apt-get install wget
        wget https://github.com/pgvector/pgvector/archive/refs/tags/v${VECTOR_VERSION}.tar.gz 
        tar -xvzf v${VECTOR_VERSION}.tar.gz
        cd pgvector-${VECTOR_VERSION}/
        make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config
        sudo make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config install
      shell: bash

    - name: Build PostGIS Extension
      run: |
        cd ..
        export CC='ccache gcc'
        export CMAKE_C_COMPILER_LAUNCHER=ccache
        export CMAKE_CXX_COMPILER_LAUNCHER=ccache 
        sudo apt-get install wget
        max_retries=20
        retries=0
        until [ $retries -ge $max_retries ]
        do
          wget http://postgis.net/stuff/postgis-3.4.0.tar.gz && break
          retries=$((retries+1))
        done
        tar -xvzf postgis-3.4.0.tar.gz
        retries1=0
        until [ $retries1 -ge $max_retries ]
        do
          wget https://download.osgeo.org/proj/proj-9.2.1.tar.gz && break
          retries1=$((retries1+1))
        done
        tar -xvzf proj-9.2.1.tar.gz
        cd proj-9.2.1
        if [ ! -d "build" ]; then
          mkdir build
        fi
        cd build
        cmake -DCMAKE_INSTALL_LIBDIR="lib/x86_64-linux-gnu" -DCMAKE_INSTALL_PREFIX="/usr" ..
        cmake --build .
        sudo cmake --build . --target install
        cd ../../postgis-3.4.0
        ./configure --without-protobuf --without-raster --with-pgconfig=$HOME/${{ inputs.install_dir }}/bin/pg_config
        make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config
        sudo make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config install
      shell: bash

    # Not used composite action install-extension here since, in the previous step it has 
    # checked out a branch/tag which may not have the updated install-extension composite action
    - name: Install extensions
      run: |
        ulimit -c unlimited
        cd ~
        export PATH=/opt/mssql-tools/bin:$PATH
        ~/${{ inputs.install_dir }}/bin/initdb -D ~/${{ inputs.install_dir }}/data/
        ~/${{ inputs.install_dir }}/bin/pg_ctl -c -D ~/${{ inputs.install_dir }}/data/ -l logfile start
        cd ${{ inputs.install_dir }}/data
        sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
        sudo sed -i "s/#shared_preload_libraries = ''/shared_preload_libraries = 'babelfishpg_tds, pg_stat_statements'/g" postgresql.conf
        ipaddress=$(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}')
        # Allow only runner to have trust authentication, all other users must provide a password
        {
          sudo echo "local   all             runner                                   trust"
          sudo echo "local   all             all                                      md5"
          sudo echo "host    all             runner          127.0.0.1/32             trust"
          sudo echo "host    all             runner          $ipaddress/32            trust"
          sudo echo "host    all             all             0.0.0.0/0                md5"
          sudo echo "host    all             all             ::/0                     md5"
        } > pg_hba.conf
        if [[ ${{ inputs.server_collation_name }} != "default" ]]; then
          sudo echo "babelfishpg_tsql.server_collation_name = '${{ inputs.server_collation_name }}'" >> ~/${{ inputs.install_dir }}/data/postgresql.conf
        fi
        ~/${{ inputs.install_dir }}/bin/pg_ctl -c -D ~/${{ inputs.install_dir }}/data/ -l logfile restart
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d postgres -U runner -c "CREATE USER jdbc_user WITH SUPERUSER CREATEDB CREATEROLE PASSWORD '12345678' INHERIT;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d postgres -U runner -c "DROP DATABASE IF EXISTS jdbc_testdb;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d postgres -U runner -c "CREATE DATABASE jdbc_testdb OWNER jdbc_user;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "set allow_system_table_mods = on;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "CREATE EXTENSION "babelfishpg_tds" CASCADE;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "GRANT ALL ON SCHEMA sys to jdbc_user;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "ALTER USER jdbc_user CREATEDB;"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "ALTER SYSTEM SET babelfishpg_tsql.database_name = 'jdbc_testdb';"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "SELECT pg_reload_conf();"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "CALL sys.initialize_babelfish('jdbc_user');"
        sudo ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "\dx"
        sqlcmd -S localhost -U jdbc_user -P 12345678 -Q "SELECT @@version GO"
      shell: bash

    - name: Change migration mode to multi-db
      id: change-migration-mode
      if: ${{ inputs.migration_mode == 'multi-db' }} && always()
      run: |
        sudo ~/${{ inputs.install_dir}}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "ALTER SYSTEM SET babelfishpg_tsql.migration_mode = 'multi-db';"
        sudo ~/${{ inputs.install_dir}}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "SELECT pg_reload_conf();"
      shell: bash

    - if: ${{ inputs.extension_branch != 'latest' && inputs.dump_restore == 'true' }}
      uses: actions/checkout@v2
      with:
        repository: babelfish-for-postgresql/babelfish_extensions
        ref: ${{ inputs.extension_branch }}

    - if: ${{ inputs.extension_branch == 'latest' || inputs.dump_restore != 'true' }}
      uses: actions/checkout@v2

    - name: Run JDBC Upgrade Tests
      id: jdbc-upgrade-tests
      env:
        base_dir: ${{ matrix.upgrade-path.path[0] }}
        migr_mode: ${{ inputs.migration_mode }}
      run: |
        cd test/JDBC/
        echo "all" > dummy_schedule
        export scheduleFile=dummy_schedule
        if [[ ${{ inputs.server_collation_name }} != "default" ]]; then
          export serverCollationName=${{ inputs.server_collation_name }}
        fi
        if [[ "$migr_mode" == "multi-db" ]];then
          export isUpgradeTestMode=true
          base_dir=${{ matrix.upgrade-path.path[0] }}
          if [[ "$base_dir" == *"latest"* || ${{ inputs.dump_restore }} == 'true' ]]; then
            base_dir="latest"
          fi
        else
          base_dir="singledb"
        fi

        export inputFilesPath=upgrade/$base_dir/preparation
        mvn -B -ntp test

        # Skip test BABEL-404 for previous versions while testing dump/restore since it specifies
        # contraint column ordering which is expected to fail after fix for BABEL-4888
        if [[ "${{ inputs.dump_restore }}" == 'true' && "${{ inputs.extension_branch }}" != 'latest' ]];then
          sed -i "/BABEL-404\>/d" upgrade/$base_dir/schedule
        fi

        for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/$base_dir/schedule); do
          if [[ ! ($(find input/ -name $filename"-vu-prepare.*") || $(find input/ -name $filename"-vu-verify.*")) ]]; then 
            printf '%s\n' "ERROR: Cannot find Test file "$filename"-vu-prepare or "$filename"-vu-verify in input directory !!" >&2
            exit 1
          fi
        done
        export isUpgradeTestMode=false
        export inputFilesPath=input
        for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/$base_dir/schedule); do
          sed -i "s/\b$filename[ ]*\b$/$filename-vu-prepare/g" upgrade/$base_dir/schedule
        done
        export scheduleFile=upgrade/$base_dir/schedule
        mvn -B -ntp test
      shell: bash

    - uses: actions/checkout@v2

    - name: Install Python
      id: install-python
      if: ${{ matrix.upgrade-path.path[0] == 'source_latest' && steps.jdbc-upgrade-tests.outcome == 'success' }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Configure Python Environment
      id: configure-python-environment
      if: always() && steps.install-python.outcome == 'success'
      run: |
        cd ~
        sudo apt-get install odbc-postgresql
        pip3 install pyodbc==4.0.35 pymssql
      shell: bash

    - name: Run dependency check
      id: run-dependency-check
      if: always() && steps.configure-python-environment.outcome == 'success'
      run: |
        cd test/python
        provider="PostgreSQL Unicode" \
        fileGenerator_URL=localhost \
        fileGenerator_port=5432 \
        fileGenerator_databaseName=jdbc_testdb \
        fileGenerator_user=jdbc_user \
        fileGenerator_password=12345678 \
        LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/odbc/ \
        python3 upgrade_validation.py
      shell: bash

    - name: Run Babelfish metadata inconsistency check
      id: check-babelfish-inconsistency
      if: always() && steps.run-dependency-check.outcome == 'success'
      uses: ./.github/composite-actions/check-babelfish-inconsistency
      
    - name: Upload artifacts
      if: |
        always() && (steps.run-dependency-check.outcome == 'failure'
        || steps.check-babelfish-inconsistency.outcome == 'failure')
      run: |
        mkdir -p ~/upgrade
        cp test/python/output/upgrade_validation/* ~/upgrade
      shell: bash
