CREATE SEQUENCE seq_949 AS INT START WITH 1 INCREMENT BY 1;
GO

CREATE TABLE table_949 (table_key INT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR seq_949, str NVARCHAR(200));
GO

INSERT INTO table_949 (str) VALUES 
('a'), 
('b'), 
('c'), 
('d');
GO

SELECT * FROM table_949 ORDER BY table_key;
GO

SELECT NEXT VALUE FOR seq_949;
GO

SELECT NEXT VALUE FOR dbo.seq_949;
GO

DROP TABLE table_949;
GO

SELECT NEXT VALUE FOR null;
GO

SELECT NEXT VALUE FOR not_a_seq;
GO

DROP SEQUENCE seq_949;
GO
