-- Drop views
DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v1;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v2;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v3;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v4;
Go

-- Drop procedures
DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p1;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p2;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p3;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p4;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p5;
Go

-- Drop functions
DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f1;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f2;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f3;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f4;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f5;
Go
