-- Drop views
DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v1;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v2;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v3;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v4;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v5;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v6;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v7;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v8_try;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v9_try;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v10_try;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v11;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v12;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v13;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v14_try;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v15_try;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v16_try;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v17;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v18;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v19;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v20;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v21;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v22;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v23;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v24;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v26;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v27;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v28;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v29;
Go

DROP VIEW IF EXISTS BABEL_BINARY_vu_prepare_v30;
Go

-- Drop procedures
DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p1;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p2;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p3;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p4;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p5;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p6;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p7;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p8;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p9;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p10;
Go

DROP PROCEDURE IF EXISTS BABEL_BINARY_vu_prepare_p11;
Go

-- Drop functions
DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f1;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f2;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f3;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f4;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f5;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f7;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f8;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f9;
Go

DROP FUNCTION IF EXISTS BABEL_BINARY_vu_prepare_f10;
Go
-- Drop test table
DROP TABLE IF EXISTS BABEL_BINARY_test_table1;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table2;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table3;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table4;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table_compcol;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table_compcol1;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table_compcol2;
GO

DROP TABLE IF EXISTS BABEL_BINARY_test_table_compcol3;
GO
