-- Versioned Windows collations Latin1_General_90_*, Latin1_General_100_* and
-- Latin1_General_140_* are accepted wherever the unversioned Latin1_General_*
-- names are, and map to the same Babelfish collations.

CREATE TABLE babel_coll_ver_t (
    id INT,
    c100_ci_as VARCHAR(50) COLLATE Latin1_General_100_CI_AS,
    c100_cs_as NVARCHAR(50) COLLATE Latin1_General_100_CS_AS,
    c140_ci_ai VARCHAR(50) COLLATE Latin1_General_140_CI_AI,
    c90_cs_ai  VARCHAR(50) COLLATE Latin1_General_90_CS_AI
);
GO

INSERT INTO babel_coll_ver_t VALUES
    (1, N'Äpfel', N'Äpfel', N'Äpfel', N'Äpfel'),
    (2, N'apfel', N'apfel', N'apfel', N'apfel'),
    (3, N'APFEL', N'APFEL', N'APFEL', N'APFEL'),
    (4, N'Apfel', N'Apfel', N'Apfel', N'Apfel');
GO

-- column collations are reported as the translated Babelfish collations
SELECT name, collation_name FROM sys.columns WHERE object_id = OBJECT_ID('babel_coll_ver_t') ORDER BY column_id;
GO

-- comparison semantics follow the CI/CS and AI/AS suffix, not the version number
SELECT id FROM babel_coll_ver_t WHERE c100_ci_as = N'apfel' ORDER BY id;
GO
SELECT id FROM babel_coll_ver_t WHERE c100_cs_as = N'apfel' ORDER BY id;
GO
SELECT id FROM babel_coll_ver_t WHERE c140_ci_ai = N'apfel' ORDER BY id;
GO
SELECT id FROM babel_coll_ver_t WHERE c90_cs_ai = N'apfel' ORDER BY id;
GO

-- COLLATE in expressions, including CAST(... AS VARCHAR(MAX)) COLLATE ... inside a
-- derived table with UNION, as generated by client applications
SELECT x.Wert
FROM (
    SELECT 0 AS Typ, CAST(c100_ci_as AS VARCHAR(MAX)) COLLATE Latin1_General_100_CI_AS AS Wert FROM babel_coll_ver_t
    UNION
    SELECT 999 AS Typ, CAST(c100_cs_as AS VARCHAR(MAX)) COLLATE Latin1_General_100_CI_AS FROM babel_coll_ver_t
) AS x
WHERE x.Wert = 'apfel'
ORDER BY x.Typ, x.Wert;
GO

-- the versioned and unversioned names behave identically
SELECT
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_100_CI_AS = 'apfel') AS v100_ci_as,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_CI_AS = 'apfel') AS ci_as,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_100_CS_AS = 'apfel') AS v100_cs_as,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_CS_AS = 'apfel') AS cs_as,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_100_CI_AI = 'apfel') AS v100_ci_ai,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_CI_AI = 'apfel') AS ci_ai,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_100_CS_AI = 'apfel') AS v100_cs_ai,
    (SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_ci_as COLLATE Latin1_General_CS_AI = 'apfel') AS cs_ai;
GO

-- ORDER BY with an explicit versioned collation
SELECT id, c100_ci_as FROM babel_coll_ver_t ORDER BY c100_ci_as COLLATE Latin1_General_140_CS_AS, id;
GO

-- variables
DECLARE @v VARCHAR(20) = 'APFEL';
SELECT COUNT(*) FROM babel_coll_ver_t WHERE c100_cs_as = @v COLLATE Latin1_General_100_CI_AS;
GO

-- catalog: fn_helpcollations and COLLATIONPROPERTY
SELECT name FROM fn_helpcollations() WHERE name LIKE 'latin1[_]general[_]90[_]%' OR name LIKE 'latin1[_]general[_]100[_]%' OR name LIKE 'latin1[_]general[_]140[_]%' ORDER BY name;
GO
SELECT CAST(COLLATIONPROPERTY('Latin1_General_100_CI_AS', 'CodePage') AS INT) AS codepage,
       CAST(COLLATIONPROPERTY('Latin1_General_100_CI_AS', 'LCID') AS INT) AS lcid,
       CAST(COLLATIONPROPERTY('Latin1_General_100_CI_AS', 'ComparisonStyle') AS INT) AS comparison_style;
GO

-- a versioned name that SQL Server does not know is still rejected
SELECT 'x' COLLATE Latin1_General_999_CI_AS;
GO

DROP TABLE babel_coll_ver_t;
GO
