SELECT * FROM DATE_BUCKET_vu_prepare_v1
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v2
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v3
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v4
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v5
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v6
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v7
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v8
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v9
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v10
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v11
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v12
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v13
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v14
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v15
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v16
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v17
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v18
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v19
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v20
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v21
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v21_trunc
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v22
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v23
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v24
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v24_trunc
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v25
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v26
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v27
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v28
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v29
GO
 
SELECT * FROM DATE_BUCKET_vu_prepare_v30
GO

SELECT * FROM DATE_BUCKET_vu_prepare_v31
GO