--Valid cases
SELECT CAST('\0' AS MONEY);
GO
SELECT CAST('$,,100' AS MONEY);
GO
SELECT ISNUMERIC(CHAR(9));
GO
SELECT ISNUMERIC(CHAR(13));
GO
SELECT isnumeric(CHAR(92));
GO
SELECT isnumeric(char(44));
GO
SELECT CAST(NCHAR(8364) AS money);           -- Euro sign
GO
SELECT CAST(CHAR(11) AS MONEY);              --Vertical tab
GO
SELECT CAST(CHAR(12) AS MONEY);              -- Form feed
GO
SELECT CAST(CHAR(32) AS MONEY);              -- Space
GO
SELECT CAST(CHAR(43) AS MONEY);              -- Plus
GO
SELECT CAST(CHAR(44) AS MONEY);              -- Comma 
GO
SELECT CAST(CHAR(45) AS MONEY);              -- Hyphen-minus
GO
SELECT CAST(CHAR(46) AS MONEY);              -- Dot
GO
SELECT CAST(CHAR(48) AS MONEY);              -- Zero
GO
SELECT CAST(CHAR(162) AS MONEY);             -- Cent sign
GO
SELECT CAST(CHAR(163) AS MONEY);             -- Pound sign
GO
SELECT CAST(CHAR(164) AS MONEY);             -- Currency sign
GO
SELECT CAST(CHAR(165) AS MONEY);             -- Yen sign
GO
SELECT CAST('\' AS money);
GO
SELECT CAST('\ .6431,,7431,85,12,97                         ' AS MONEY);
GO
SELECT CAST(NCHAR(160) + ' ' AS MONEY);
GO
--Invalid cases
SELECT CAST(NCHAR(160) + '123.45' AS MONEY);
GO
SELECT CAST(NCHAR(160) + NCHAR(160) + '99.99' AS MONEY);
GO
SELECT CAST(NCHAR(160) + '123.45' + NCHAR(160) AS MONEY);
GO
SELECT CAST(NCHAR(160) + 'hello' AS MONEY)
GO
SELECT CAST('\\1234' AS MONEY);
GO
SELECT CAST(',/,1234' AS MONEY);
GO
SELECT CAST('1234\0' AS MONEY);
GO
SELECT CAST('1234\ ' AS MONEY);
GO
SELECT CAST('1234/5,6 ' AS MONEY); 
GO
SELECT CAST('1234abc' AS MONEY);
GO
SELECT CAST('1234\\' AS MONEY);
GO
SELECT CAST(CHAR(72) AS MONEY);
GO
SELECT CAST(CHAR(73) AS MONEY);
GO
SELECT CAST(CHAR(74) AS MONEY);
GO
SELECT CAST(CHAR(75) AS MONEY);
GO
SELECT CAST(CHAR(76) AS MONEY);
GO
SELECT CAST(CHAR(77) AS MONEY);
GO
SELECT CAST(CHAR(78) AS MONEY);
GO
SELECT CAST(CHAR(79) AS MONEY);
GO
SELECT CAST(CHAR(80) AS MONEY);
GO
SELECT CAST(CHAR(81) AS MONEY);
GO
SELECT CAST(CHAR(82) AS MONEY);
GO
SELECT CAST(CHAR(83) AS MONEY);
GO
SELECT CAST(CHAR(84) AS MONEY);
GO
SELECT CAST(CHAR(85) AS MONEY);
GO
SELECT CAST(CHAR(86) AS MONEY);
GO
SELECT CAST(CHAR(87) AS MONEY);
GO
SELECT CAST(CHAR(88) AS MONEY);
GO
SELECT CAST(CHAR(89) AS MONEY);
GO
SELECT CAST(CHAR(90) AS MONEY);
GO
SELECT CAST(CHAR(91) AS MONEY);
GO
SELECT CAST(CHAR(93) AS MONEY);
GO
SELECT CAST(CHAR(94) AS MONEY);
GO
SELECT CAST(CHAR(95) AS MONEY);
GO
SELECT CAST(CHAR(96) AS MONEY);
GO
SELECT CAST(CHAR(97) AS MONEY);
GO
SELECT CAST(CHAR(98) AS MONEY);
GO
SELECT CAST(CHAR(99) AS MONEY);
GO
SELECT CAST(CHAR(100) AS MONEY);
GO
SELECT CAST(CHAR(101) AS MONEY);
GO
SELECT CAST(CHAR(102) AS MONEY);
GO
SELECT CAST(CHAR(103) AS MONEY);
GO
SELECT CAST(CHAR(104) AS MONEY);
GO
SELECT CAST(CHAR(105) AS MONEY);
GO
SELECT CAST(CHAR(106) AS MONEY);
GO
SELECT CAST(CHAR(107) AS MONEY);
GO
SELECT CAST(CHAR(108) AS MONEY);
GO
SELECT CAST(CHAR(109) AS MONEY);
GO
SELECT CAST(CHAR(110) AS MONEY);
GO
SELECT CAST(CHAR(111) AS MONEY);
GO
SELECT CAST(CHAR(112) AS MONEY);
GO
SELECT CAST(CHAR(113) AS MONEY);
GO
SELECT CAST(CHAR(114) AS MONEY);
GO
SELECT CAST(CHAR(115) AS MONEY);
GO
SELECT CAST(CHAR(116) AS MONEY);
GO
SELECT CAST(CHAR(117) AS MONEY);
GO
SELECT CAST(CHAR(118) AS MONEY);
GO
SELECT CAST(CHAR(119) AS MONEY);
GO
SELECT CAST(CHAR(120) AS MONEY);
GO
SELECT CAST(CHAR(121) AS MONEY);
GO
SELECT CAST(CHAR(122) AS MONEY);
GO
SELECT CAST(CHAR(123) AS MONEY);
GO
SELECT CAST(CHAR(124) AS MONEY);
GO
SELECT CAST(CHAR(125) AS MONEY);
GO
SELECT CAST(CHAR(126) AS MONEY);
GO
SELECT CAST(CHAR(127) AS MONEY);
GO
SELECT CAST(CHAR(129) AS MONEY);
GO
SELECT CAST(CHAR(130) AS MONEY);
GO
SELECT CAST(CHAR(131) AS MONEY);
GO
SELECT CAST(CHAR(132) AS MONEY);
GO
SELECT CAST(CHAR(133) AS MONEY);
GO
SELECT CAST(CHAR(134) AS MONEY);
GO
SELECT CAST(CHAR(135) AS MONEY);
GO
SELECT CAST(CHAR(136) AS MONEY);
GO
SELECT CAST(CHAR(137) AS MONEY);
GO
SELECT CAST(CHAR(138) AS MONEY);
GO
SELECT CAST(CHAR(139) AS MONEY);
GO
SELECT CAST(CHAR(140) AS MONEY);
GO
SELECT CAST(CHAR(142) AS MONEY);
GO
SELECT CAST(CHAR(145) AS MONEY);
GO
SELECT CAST(CHAR(146) AS MONEY);
GO
SELECT CAST(CHAR(147) AS MONEY);
GO
SELECT CAST(CHAR(148) AS MONEY);
GO
SELECT CAST(CHAR(149) AS MONEY);
GO
SELECT CAST(CHAR(150) AS MONEY);
GO
SELECT CAST(CHAR(151) AS MONEY);
GO
SELECT CAST(CHAR(152) AS MONEY);
GO
SELECT CAST(CHAR(153) AS MONEY);
GO
SELECT CAST(CHAR(154) AS MONEY);
GO
SELECT CAST(CHAR(155) AS MONEY);
GO
SELECT CAST(CHAR(156) AS MONEY);
GO
SELECT CAST(CHAR(158) AS MONEY);
GO
SELECT CAST(CHAR(159) AS MONEY);
GO
SELECT CAST(CHAR(161) AS MONEY);
GO
SELECT CAST(CHAR(166) AS MONEY);
GO
SELECT CAST(CHAR(167) AS MONEY);
GO
SELECT CAST(CHAR(168) AS MONEY);
GO
SELECT CAST(CHAR(169) AS MONEY);
GO
SELECT CAST(CHAR(170) AS MONEY);
GO
SELECT CAST(CHAR(171) AS MONEY);
GO
SELECT CAST(CHAR(172) AS MONEY);
GO
SELECT CAST(CHAR(173) AS MONEY);
GO
SELECT CAST(CHAR(174) AS MONEY);
GO
SELECT CAST(CHAR(175) AS MONEY);
GO
SELECT CAST(CHAR(176) AS MONEY);
GO
SELECT CAST(CHAR(177) AS MONEY);
GO
SELECT CAST(CHAR(178) AS MONEY);
GO
SELECT CAST(CHAR(179) AS MONEY);
GO
SELECT CAST(CHAR(180) AS MONEY);
GO
SELECT CAST(CHAR(181) AS MONEY);
GO
SELECT CAST(CHAR(182) AS MONEY);
GO
SELECT CAST(CHAR(183) AS MONEY);
GO
SELECT CAST(CHAR(184) AS MONEY);
GO
SELECT CAST(CHAR(185) AS MONEY);
GO
SELECT CAST(CHAR(186) AS MONEY);
GO
SELECT CAST(CHAR(187) AS MONEY);
GO
SELECT CAST(CHAR(188) AS MONEY);
GO
SELECT CAST(CHAR(189) AS MONEY);
GO
SELECT CAST(CHAR(190) AS MONEY);
GO
SELECT CAST(CHAR(191) AS MONEY);
GO
SELECT CAST(CHAR(192) AS MONEY);
GO
SELECT CAST(CHAR(193) AS MONEY);
GO
SELECT CAST(CHAR(194) AS MONEY);
GO
SELECT CAST(CHAR(195) AS MONEY);
GO
SELECT CAST(CHAR(196) AS MONEY);
GO
SELECT CAST(CHAR(197) AS MONEY);
GO
SELECT CAST(CHAR(198) AS MONEY);
GO
SELECT CAST(CHAR(199) AS MONEY);
GO
SELECT CAST(CHAR(200) AS MONEY);
GO
SELECT CAST(CHAR(201) AS MONEY);
GO
SELECT CAST(CHAR(202) AS MONEY);
GO
SELECT CAST(CHAR(203) AS MONEY);
GO
SELECT CAST(CHAR(204) AS MONEY);
GO
SELECT CAST(CHAR(205) AS MONEY);
GO
SELECT CAST(CHAR(206) AS MONEY);
GO
SELECT CAST(CHAR(207) AS MONEY);
GO
SELECT CAST(CHAR(208) AS MONEY);
GO
SELECT CAST(CHAR(209) AS MONEY);
GO
SELECT CAST(CHAR(210) AS MONEY);
GO
SELECT CAST(CHAR(211) AS MONEY);
GO
SELECT CAST(CHAR(212) AS MONEY);
GO
SELECT CAST(CHAR(213) AS MONEY);
GO
SELECT CAST(CHAR(214) AS MONEY);
GO
SELECT CAST(CHAR(215) AS MONEY);
GO
SELECT CAST(CHAR(216) AS MONEY);
GO
SELECT CAST(CHAR(217) AS MONEY);
GO
SELECT CAST(CHAR(218) AS MONEY);
GO
SELECT CAST(CHAR(219) AS MONEY);
GO
SELECT CAST(CHAR(220) AS MONEY);
GO
SELECT CAST(CHAR(221) AS MONEY);
GO
SELECT CAST(CHAR(222) AS MONEY);
GO
SELECT CAST(CHAR(223) AS MONEY);
GO
SELECT CAST(CHAR(224) AS MONEY);
GO
SELECT CAST(CHAR(225) AS MONEY);
GO
SELECT CAST(CHAR(226) AS MONEY);
GO
SELECT CAST(CHAR(227) AS MONEY);
GO
SELECT CAST(CHAR(228) AS MONEY);
GO
SELECT CAST(CHAR(229) AS MONEY);
GO
SELECT CAST(CHAR(230) AS MONEY);
GO
SELECT CAST(CHAR(231) AS MONEY);
GO
SELECT CAST(CHAR(232) AS MONEY);
GO
SELECT CAST(CHAR(241) AS MONEY);
GO
SELECT CAST(CHAR(242) AS MONEY);
GO
SELECT CAST(CHAR(243) AS MONEY);
GO
SELECT CAST(CHAR(244) AS MONEY);
GO
SELECT CAST(CHAR(245) AS MONEY);
GO
SELECT CAST(CHAR(246) AS MONEY);
GO
SELECT CAST(CHAR(247) AS MONEY);
GO
SELECT CAST(CHAR(248) AS MONEY);
GO
SELECT CAST(CHAR(249) AS MONEY);
GO

SELECT * FROM dbo.fn_tests_moneydecl();
GO

SELECT * FROM dbo.vw_test_money_whitespace;
GO

EXEC dbo.sp_test_money_special;
GO

SELECT * FROM dbo.vw_test_money_currency;
GO

EXEC dbo.sp_test_money_digits;
GO