CREATE VIEW BABEL_3748_vu_prepare_v1 as (SELECT TRY_CAST(1 as XML));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p1 as (SELECT TRY_CAST(1 as XML));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f1()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CAST(1 as XML));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v2 as (SELECT TRY_CAST(1.1 as XML));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p2 as (SELECT TRY_CAST(1.1 as XML));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f2()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CAST(1.1 as XML));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v3 as (SELECT TRY_CAST(1 as MONEY));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p3 as (SELECT TRY_CAST(1 as MONEY));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f3()
RETURNS MONEY AS
BEGIN
RETURN (SELECT TRY_CAST(1 as MONEY));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v4 as (SELECT TRY_CAST(1.1 as MONEY));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p4 as (SELECT TRY_CAST(1.1 as MONEY));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f4()
RETURNS MONEY AS
BEGIN
RETURN (SELECT TRY_CAST(1.1 as MONEY));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v5 as (SELECT TRY_CAST((1+2) as XML));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p5 as (SELECT TRY_CAST((1+2) as XML));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f5()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CAST((1+2) as XML));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v6 as (SELECT TRY_CONVERT(XML, 1));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p6 as (SELECT TRY_CONVERT(XML, 1));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f6()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CONVERT(XML, 1));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v7 as (SELECT TRY_CONVERT(XML, 1.1));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p7 as (SELECT TRY_CONVERT(XML, 1.1));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f7()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CONVERT(XML, 1.1));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v8 as (SELECT TRY_CONVERT(MONEY, 1));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p8 as (SELECT TRY_CONVERT(MONEY, 1));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f8()
RETURNS MONEY AS
BEGIN
RETURN (SELECT TRY_CONVERT(MONEY, 1));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v9 as (SELECT TRY_CONVERT(MONEY, 1.1));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p9 as (SELECT TRY_CONVERT(MONEY, 1.1));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f9()
RETURNS MONEY AS
BEGIN
RETURN (SELECT TRY_CONVERT(MONEY, 1.1));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v10 as (SELECT TRY_CONVERT(XML, (1+2)));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p10 as (SELECT TRY_CONVERT(XML, (1+2)));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f10()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CONVERT(XML, (1+2)));
END
GO

CREATE VIEW BABEL_3748_vu_prepare_v11 as (SELECT TRY_CONVERT(XML, (1.1+2.2)));
GO
CREATE PROCEDURE BABEL_3748_vu_prepare_p11 as (SELECT TRY_CONVERT(XML, (1.1+2.2)));
GO
CREATE FUNCTION BABEL_3748_vu_prepare_f11()
RETURNS XML AS
BEGIN
RETURN (SELECT TRY_CONVERT(XML, (1.1+2.2)));
END
GO