CREATE SEQUENCE seq_949 AS INT START WITH 1 INCREMENT BY 1;
GO
CREATE TABLE table_949 (table_key INT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR seq_949, str NVARCHAR(200));
GO

INSERT INTO table_949 (str) VALUES
('a'),
('b'),
('c'),
('d');
GO

