CREATE SCHEMA babel_949;
GO
CREATE SEQUENCE babel_949.seq1 AS INT START WITH 100 INCREMENT BY 5;
GO
CREATE SEQUENCE seq_949 AS INT START WITH 1 INCREMENT BY 1;
GO
CREATE TABLE table_949 (table_key INT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR seq_949, str NVARCHAR(200));
GO

INSERT INTO table_949 (str) VALUES
('a'),
('b'),
('c'),
('d');
GO

CREATE DATABASE babel_949_db;
GO

use babel_949_db;
GO

create schema babel_949_2;
go

CREATE SEQUENCE babel_949_2.seq2 AS INT START WITH 10 INCREMENT BY 5 MINVALUE 0 MAXVALUE 100;
go

CREATE SEQUENCE seq3 AS INT START WITH 0 INCREMENT BY 1 MINVALUE 0 MAXVALUE 100;
go

USE master;
GO
