ALTER SERVER ROLE sysadmin DROP MEMBER jdbc_user;
GO

CREATE LOGIN test2569 with PASSWORD = '123';
GO

ALTER SERVER ROLE sysadmin ADD MEMBER test2569;
GO

ALTER SERVER ROLE sysadmin DROP MEMBER test2569;
GO

DROP LOGIN test2569;
GO

ALTER SERVER ROLE sysadmin DROP MEMBER jdbc_user;
GO
