-- Drop Views
DROP VIEW BABEL_5597_binary_test_view1;
GO
DROP VIEW BABEL_5597_binary_test_view2;
GO
DROP VIEW BABEL_5597_binary_test_view3;
GO
DROP VIEW BABEL_5597_binary_test_view4;
GO
DROP VIEW BABEL_5597_binary_test_view5;
GO
DROP VIEW BABEL_5597_binary_test_view6;
GO
DROP VIEW BABEL_5597_binary_test_view7;
GO
DROP VIEW BABEL_5597_binary_test_view8;
GO
DROP VIEW BABEL_5597_mixed_test_view1;
GO
DROP VIEW BABEL_5597_mixed_test_view2;
GO
DROP VIEW BABEL_5597_mixed_test_view3;
GO
DROP VIEW BABEL_5597_mixed_test_view4;
GO
DROP VIEW BABEL_5597_mixed_test_view5;
GO
DROP VIEW BABEL_5597_mixed_test_view6;
GO
DROP VIEW BABEL_5597_mixed_test_view7;
GO
DROP VIEW BABEL_5597_mixed_test_view8;
GO

-- Drop Functions
DROP FUNCTION BABEL_5597_binary_test_func1;
GO
DROP FUNCTION BABEL_5597_binary_test_func2;
GO
DROP FUNCTION BABEL_5597_binary_test_func3;
GO
DROP FUNCTION BABEL_5597_binary_test_func4;
GO
DROP FUNCTION BABEL_5597_binary_test_func5;
GO
DROP FUNCTION BABEL_5597_binary_test_func6;
GO
DROP FUNCTION BABEL_5597_binary_test_func7;
GO
DROP FUNCTION BABEL_5597_binary_test_func8;
GO
DROP FUNCTION BABEL_5597_binary_test_func9;
GO
DROP FUNCTION BABEL_5597_mixed_test_func1;
GO
DROP FUNCTION BABEL_5597_mixed_test_func2;
GO
DROP FUNCTION BABEL_5597_mixed_test_func3;
GO
DROP FUNCTION BABEL_5597_mixed_test_func4;
GO
DROP FUNCTION BABEL_5597_mixed_test_func5;
GO
DROP FUNCTION BABEL_5597_mixed_test_func6;
GO
DROP FUNCTION BABEL_5597_mixed_test_func7;
GO
DROP FUNCTION BABEL_5597_mixed_test_func8;
GO
DROP FUNCTION BABEL_5597_mixed_test_func9;
GO

-- Drop Procedures
DROP PROCEDURE BABEL_5597_binary_test_proc1;
GO
DROP PROCEDURE BABEL_5597_binary_test_proc2;
GO
DROP PROCEDURE BABEL_5597_binary_test_proc3;
GO
DROP PROCEDURE BABEL_5597_binary_test_proc4;
GO
DROP PROCEDURE BABEL_5597_binary_test_proc5;
GO
DROP PROCEDURE BABEL_5597_binary_test_proc6;
GO
DROP PROCEDURE BABEL_5597_binary_test_proc7;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc1;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc2;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc3;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc4;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc5;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc6;
GO
DROP PROCEDURE BABEL_5597_mixed_test_proc7;
GO

-- Drop indexes
DROP INDEX BABEL_5597_binary_ind ON BABEL_5597_binary_test;
GO


-- Drop Tables
DROP TABLE BABEL_5597_binary_test_table;
GO
DROP TABLE BABEL_5597_mixed_test_table;
GO
DROP TABLE BABEL_5597_binary_test;
GO

-- Drop UDTs
DROP TYPE FIXEDLEN_BINARY
GO
DROP TYPE MAXLEN_BINARY
GO
DROP TYPE FIXEDLEN_VARBINARY
GO
DROP TYPE MAXLEN_VARBINARY
GO

Drop trigger after_trig
GO
DROP TABLE t11
GO
DROP TABLE t12
GO