-- BABEL-1661
-- Test CONVERT to VARCHAR applies typmod
SELECT CONVERT(VARCHAR(10), SERVERPROPERTY('productversion'));
GO

SELECT DATALENGTH(CONVERT(VARCHAR(10), SERVERPROPERTY('productversion')));
GO

SELECT CONVERT(VARCHAR(2), SERVERPROPERTY('productversion'));
GO

SELECT DATALENGTH(CONVERT(VARCHAR(2), SERVERPROPERTY('productversion')));
GO
