SELECT CASE 1
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 2
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 3
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 4
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 5
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 6
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 1
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 2
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 3
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 4
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 5
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 6
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
   WHEN 5 THEN COL5
   WHEN 6 THEN COL6
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 1
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 2
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 3
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 4
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 1
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 2
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 3
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 4
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
   WHEN 3 THEN COL3
   WHEN 4 THEN COL4
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 1
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 1
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
END AS RESULT FROM BABEL_5103_V1
GO

SELECT CASE 2
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
END AS RESULT FROM BABEL_5103_T1
GO

SELECT CASE 2
   WHEN 1 THEN COL1 
   WHEN 2 THEN COL2
END AS RESULT FROM BABEL_5103_V1
GO

-- Function call
SELECT BABEL_5103_F1('REGULAR');
GO

SELECT BABEL_5103_F1(N'登録カード–標準');
GO

SELECT BABEL_5103_F1(N'بطاقة التسجيل - قياسية');
GO

-- selecting from view
SELECT * FROM BABEL_5103_V2
GO

-- single branch
SELECT CASE 1
   WHEN 1 THEN CAST('char' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char' AS NTEXT)
END AS RESULT
GO

-- single branch with multibyte character
SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- multiple branch without NULL one being NVARCHAR
SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- multiple branch without NULL one being VARCHAR
SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS VARCHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- multiple branch without NULL one being CHAR
SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS Char(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS CHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS CHAR(100))
   WHEN 2 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS Char(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS CHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS CHAR(100))
   WHEN 2 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

-- multiple branch without NULL one being NCHAR
SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NCHAR(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS NCHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NCHAR(100))
   WHEN 2 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS NCHAR(100))
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- multiple branch without NULL one being TEXT
SELECT CASE 1
   WHEN 1 THEN CAST('char0' AS TEXT)
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(N'登録カード–標準' AS TEXT)
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('char0' AS TEXT)
   WHEN 2 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(N'登録カード–標準' AS TEXT)
   WHEN 2 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- multiple branch with one being string literal
SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO


SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS Char(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO


SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS Char(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN 'abc'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 3
   WHEN 1 THEN N'登録カード–標準'
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- multiple branches one being NULL
SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO


SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS Char(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- NULL tests
SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NVARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS VARCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS Char(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS CHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS NCHAR(100))
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST('char0' AS TEXT)
   WHEN 3 THEN CAST('char1' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
END AS RESULT
GO


SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS Char(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS CHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS NCHAR(100))
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'بطاقة التسجيل - قياسية' AS TEXT)
   WHEN 3 THEN CAST(N'بطاقة التسجيل - قياسية' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NCHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NVARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS CHAR(100))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS VARCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS Char(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS CHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS TEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS NCHAR(100))
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN NULL
   WHEN 2 THEN CAST(N'登録カード–標準' AS TEXT)
   WHEN 3 THEN CAST(N'登録カード–標準' AS NTEXT)
END AS RESULT
GO

-- other datatypes then string 
SELECT CASE 1
   WHEN 1 THEN CAST(123 AS INT)
   WHEN 2 THEN CAST(456 AS DECIMAL(10, 2))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(123.456 AS FLOAT)
   WHEN 2 THEN CAST(789.123 AS NUMERIC(10, 3))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(123 AS SMALLINT)
   WHEN 2 THEN CAST(456789123 AS BIGINT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(123 AS SMALLINT)
   WHEN 2 THEN CAST(456 AS DECIMAL(10, 2))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(123.456 AS BIGINT)
   WHEN 2 THEN CAST(789.123 AS NUMERIC(10, 3))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(123 AS SMALLINT)
   WHEN 2 THEN CAST(456789123 AS BIGINT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('2024-01-01' AS DATE)
   WHEN 2 THEN CAST('2024-09-27 12:34:56' AS DATETIME)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST('12:34:56' AS TIME)
   WHEN 2 THEN CAST('2024-09-27 12:34:56.1234567' AS DATETIME2(7))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(1 AS BIT)
   WHEN 2 THEN CAST(0 AS BIT)
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(0x123456 AS BINARY(3))
   WHEN 2 THEN CAST(0xABCDEF AS VARBINARY(6))
END AS RESULT
GO

SELECT CASE 1
   WHEN 1 THEN CAST(1000.00 AS MONEY)
   WHEN 2 THEN CAST(100.00 AS SMALLMONEY)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(123 AS INT)
   WHEN 2 THEN CAST(456 AS DECIMAL(10, 2))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(123.456 AS FLOAT)
   WHEN 2 THEN CAST(789.123 AS NUMERIC(10, 3))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(123 AS SMALLINT)
   WHEN 2 THEN CAST(456789123 AS BIGINT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(123 AS SMALLINT)
   WHEN 2 THEN CAST(456 AS DECIMAL(10, 2))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(123.456 AS BIGINT)
   WHEN 2 THEN CAST(789.123 AS NUMERIC(10, 3))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(123 AS SMALLINT)
   WHEN 2 THEN CAST(456789123 AS BIGINT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('2024-01-01' AS DATE)
   WHEN 2 THEN CAST('2024-09-27 12:34:56' AS DATETIME)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST('12:34:56' AS TIME)
   WHEN 2 THEN CAST('2024-09-27 12:34:56.1234567' AS DATETIME2(7))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(1 AS BIT)
   WHEN 2 THEN CAST(0 AS BIT)
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(0x123456 AS BINARY(3))
   WHEN 2 THEN CAST(0xABCDEF AS VARBINARY(6))
END AS RESULT
GO

SELECT CASE 2
   WHEN 1 THEN CAST(1000.00 AS MONEY)
   WHEN 2 THEN CAST(100.00 AS SMALLMONEY)
END AS RESULT
GO

-- Collation tests
-- FIX ME: Following test cases shows behaviour mismatch,
-- When we compare N'  比尔·拉莫斯    ' COLLATE japanese_ci_as
-- with N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS  for CASE expression,
-- Gives 'true' (as used in PG), whereas it should give 'false' (as in TSQL).

SELECT CASE 'abcd' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN CAST('abcd' AS VARCHAR(100))
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  比尔·拉莫斯    ' AS VARCHAR(100))
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  abc🙂defghi🙂🙂    ' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN CAST('abcd' AS VARCHAR(100))
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  比尔·拉莫斯    ' AS VARCHAR(100))
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  abc🙂defghi🙂🙂    ' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN CAST('abcd' AS VARCHAR(100))
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  比尔·拉莫斯    ' AS VARCHAR(100))
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  abc🙂defghi🙂🙂    ' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN CAST('abcd' AS VARCHAR(100))
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  比尔·拉莫斯    ' AS VARCHAR(100))
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  abc🙂defghi🙂🙂    ' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN CAST('abcd' AS VARCHAR(100))
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  比尔·拉莫斯    ' AS VARCHAR(100))
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  abc🙂defghi🙂🙂    ' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN CAST('abcd' AS VARCHAR(100))
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  比尔·拉莫斯    ' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  比尔·拉莫斯    ' AS VARCHAR(100))
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN CAST(N'بطاقة التسجيل - قياسية' AS VARCHAR(100))
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    '
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    '
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية'
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN CAST(N'  abc🙂defghi🙂🙂    ' AS VARCHAR(100))
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd' COLLATE CHINESE_PRC_CI_AS
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE japanese_ci_as
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd' COLLATE japanese_ci_as
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    ' COLLATE japanese_ci_as
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية' COLLATE japanese_ci_as
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    ' COLLATE japanese_ci_as
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd'
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
END AS RESULT
GO

SELECT CASE N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd' COLLATE japanese_ci_as
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    ' COLLATE japanese_ci_as
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية' COLLATE japanese_ci_as
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    ' COLLATE japanese_ci_as
END AS RESULT
GO

SELECT CASE N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd' COLLATE ARABIC_CI_AS
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    ' COLLATE ARABIC_CI_AS
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    ' COLLATE ARABIC_CI_AS
END AS RESULT
GO

SELECT CASE 'abcd' COLLATE ARABIC_CI_AS
   WHEN 'abcd' COLLATE japanese_ci_as THEN 'abcd' COLLATE CHINESE_PRC_CI_AS
   WHEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS THEN N'  比尔·拉莫斯    ' COLLATE CHINESE_PRC_CI_AS
   WHEN N'بطاقة التسجيل - قياسية' COLLATE ARABIC_CI_AS THEN N'بطاقة التسجيل - قياسية' COLLATE CHINESE_PRC_CI_AS
   WHEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS THEN N'  abc🙂defghi🙂🙂    ' COLLATE CHINESE_PRC_CI_AS
END AS RESULT
GO
