SELECT * FROM BABEL_3478_t1;
SELECT ROWCOUNT_BIG();
GO

SELECT * FROM BABEL_3478_InfoView;
SELECT ROWCOUNT_BIG();
GO


EXEC Insert_BABEL_3478_p1;
SELECT ROWCOUNT_BIG();
GO



SELECT * FROM Updated_BABEL_3478_InfoView;
SELECT ROWCOUNT_BIG();
GO

EXEC Update_BABEL_3478_Salary 'Doe', 700000;
SELECT ROWCOUNT_BIG();
GO

EXEC Delete_BABEL_3478_p2 'Doe';
SELECT ROWCOUNT_BIG();
GO