CREATE PROCEDURE BABEL_SET_CONTEXT_INFO
    @context_info varbinary(128)
AS
BEGIN
    EXEC sys.bbf_set_context_info @context_info
END;
GO

CREATE PROCEDURE BABEL_GET_CONTEXT_INFO_WITH_PLP
AS
BEGIN
    SELECT sys.bbf_get_context_info()
END;
GO

CREATE PROCEDURE BABEL_GET_CONTEXT_INFO
AS
BEGIN
    SELECT CONTEXT_INFO()
END;
GO

CREATE VIEW BABEL_CONTEXT_INFO_VIEW AS
    SELECT CONTEXT_INFO()
GO
