-- Prepare: Create partition function and scheme for PERSISTED computed column tests

SET QUOTED_IDENTIFIER ON
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
GO

-- Partition function and scheme
CREATE PARTITION FUNCTION pcc_part_func (INT)
AS RANGE RIGHT FOR VALUES (10, 20, 30, 40)
GO

CREATE PARTITION SCHEME pcc_part_scheme
AS PARTITION pcc_part_func ALL TO ([PRIMARY])
GO
