EXEC test_prep_statements_vu_prepare_p1
GO

EXEC test_prep_statements_vu_prepare_p2
GO

EXEC test_prep_statements_vu_prepare_p3
GO

EXEC test_prep_statements_vu_prepare_p4
GO

EXEC test_prep_statements_vu_prepare_p5
GO

EXEC test_prep_statements_vu_prepare_p6
GO

EXEC test_prep_statements_vu_prepare_p7
GO

EXEC test_prep_statements_vu_prepare_p8
GO

EXEC test_prep_statements_vu_prepare_p9
GO

EXEC test_prep_statements_vu_prepare_p10
GO

EXEC test_prep_statements_vu_prepare_p11
GO

EXEC test_prep_statements_vu_prepare_p12
GO

EXEC test_prep_statements_vu_prepare_p13
GO

EXEC test_prep_statements_vu_prepare_p14
GO

EXEC test_prep_statements_vu_prepare_p15
GO

EXEC test_prep_statements_vu_prepare_p16
GO

EXEC test_prep_statements_vu_prepare_p17
GO

EXEC test_prep_statements_vu_prepare_p18
GO

EXEC test_prep_statements_vu_prepare_p19
GO

EXEC test_prep_statements_vu_prepare_p20
GO

EXEC test_prep_statements_vu_prepare_p21
GO

EXEC test_prep_statements_vu_prepare_p22
GO

EXEC test_prep_statements_vu_prepare_p23
GO

EXEC test_prep_statements_vu_prepare_p24
GO

EXEC test_prep_statements_vu_prepare_p25
GO

EXEC test_prep_statements_vu_prepare_p26
GO

