CREATE TABLE Timecheck(
    Name VARCHAR(50),
    CheckTime DATETIME DEFAULT CURRENT_TIMESTAMP
)
GO

CREATE TABLE Timecheck1(
    Name VARCHAR(50),
    CheckTime DATETIME DEFAULT CURRENT_TIMESTAMP
)
GO

CREATE TABLE Timecheck2(
    Name VARCHAR(50),
    CheckTime DATETIME DEFAULT CURRENT_TIMESTAMP
)
GO

CREATE TABLE Timecheck3(
    Name VARCHAR(50),
    CheckTime DATETIME DEFAULT CURRENT_TIMESTAMP
)
GO

CREATE TABLE Timecheck4(
    Name VARCHAR(50),
    CheckTime DATETIME DEFAULT CURRENT_TIMESTAMP
)
GO

CREATE TABLE Timecheck5(
    Name VARCHAR(50),
    CheckTime DATETIME DEFAULT CURRENT_TIMESTAMP
)
GO


CREATE PROCEDURE TimeDelay
    (
    @Delaytime char(8)= '00:00:00'
    )
AS
BEGIN
    WAITFOR DELAY @Delaytime
END;
GO


CREATE PROCEDURE Wait2seconds
    (
    @resumetime datetime
    )
AS
BEGIN
    WAITFOR TIME @resumetime
END;
GO