CREATE TABLE sys.babelfish_xml_handles (
    session_id INT NOT NULL,
    document_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 2),
    namespace_document_id INT GENERATED ALWAYS AS (
        CASE
            WHEN NamespaceDefinitions IS NOT NULL THEN document_id + 1
            ELSE NULL
        END
    ) STORED,
    Xml_content XML,
    NamespaceDefinitions XML,
    sql_handle BYTEA,
    statement_start_offset INT DEFAULT NULL,
    statement_end_offset INT DEFAULT NULL,
    creation_time TIMESTAMP DEFAULT CAST(sys.sysutcdatetime() AS sys.datetime),
    original_document_size_bytes BIGINT NULL,
    original_namespace_document_size_bytes BIGINT NULL,
    num_openxml_calls BIGINT DEFAULT 0,
    row_count BIGINT DEFAULT 0,
    dormant_duration_ms BIGINT DEFAULT 0,
    PRIMARY KEY(session_id, document_id)
);


GRANT SELECT, INSERT, DELETE ON sys.babelfish_xml_handles TO PUBLIC;

SELECT pg_catalog.pg_extension_config_dump('sys.babelfish_xml_handles', '');