name: 'Install Extensions'

runs:
  using: "composite"
  steps:
    - name: Install Extensions
      run: |
        cd ~
        export PATH=/opt/mssql-tools/bin:$PATH
        ~/postgres/bin/initdb -D ~/postgres/data/
        ~/postgres/bin/pg_ctl -D ~/postgres/data/ -l logfile start
        cd postgres/data
        sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
        sudo sed -i "s/#shared_preload_libraries = ''/shared_preload_libraries = 'babelfishpg_tds'/g" postgresql.conf
        ipaddress=$(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}')
        sudo echo "host    all             all             $ipaddress/32            trust" >> pg_hba.conf
        ~/postgres/bin/pg_ctl -D ~/postgres/data/ -l logfile restart
        cd ~/work/babelfish_extensions/babelfish_extensions/
        sudo ~/postgres/bin/psql -d postgres -U runner -v user="jdbc_user" -v db="jdbc_testdb" -f .github/scripts/create_extension.sql
        sqlcmd -S localhost -U "jdbc_user" -P 12345678 -Q "SELECT @@version GO"
      shell: bash
