name: 'Install Extensions'

inputs:
  install_dir:
    description: 'Engine install directory'
    required: no
    default: postgres
  migration_mode:
    description: 'Database migration mode'
    required: no
    default: "single-db"
  parallel_query_mode:
    description: 'Postgres Parallel Query Mode'
    required: no
    default: false
  server_collation_name:
    description: "Server collation name which need to be set in postgresql.conf"
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Install Extensions
      run: |
        cd ~
        export PATH=/opt/mssql-tools/bin:$PATH
        ~/${{inputs.install_dir}}/bin/initdb -D ~/${{inputs.install_dir}}/data/
        ~/${{inputs.install_dir}}/bin/pg_ctl -D ~/${{inputs.install_dir}}/data/ -l logfile start
        cd ${{inputs.install_dir}}/data
        sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
        sudo sed -i "s/#shared_preload_libraries = ''/shared_preload_libraries = 'babelfishpg_tds'/g" postgresql.conf
        ipaddress=$(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}')
        sudo echo "host    all             all             $ipaddress/32            trust" >> pg_hba.conf
        if [[ ${{ inputs.server_collation_name }} != "default" ]]; then
          sudo echo "babelfishpg_tsql.server_collation_name = '${{ inputs.server_collation_name }}'" >> postgresql.conf
        fi
        ~/${{inputs.install_dir}}/bin/pg_ctl -D ~/${{inputs.install_dir}}/data/ -l logfile restart
        cd ~/work/babelfish_extensions/babelfish_extensions/
        sudo ~/${{inputs.install_dir}}/bin/psql -d postgres -U runner -v user="jdbc_user" -v db="jdbc_testdb" -v migration_mode=${{inputs.migration_mode}} -v parallel_query_mode=${{inputs.parallel_query_mode}} -f .github/scripts/create_extension.sql
        sqlcmd -S localhost -U "jdbc_user" -P 12345678 -Q "SELECT @@version GO"
      shell: bash
