name: 'Build pgaudit Extension'

inputs:
  install_dir:
    description: 'Engine install directory'
    required: no
    default: psql

runs:
  using: "composite"
  steps:
    - name: Build pgaudit Extension
      run: |
        cd ~
        rm -rf pgaudit
        sudo apt-get install -y git make gcc
        git clone --depth 1 --branch REL_16_STABLE https://github.com/pgaudit/pgaudit.git
        echo "repo cloned successfully"
        ls
        cd pgaudit
        echo "came into pgaudit repo successfully"
        pwd
        ls
        echo "pgaudit complied successfully"
        make install USE_PGXS=1 PG_CONFIG=~/psql/bin/pg_config 
        echo "pgaudit installed successfully"
        cd ..
        ls
        cd psql
        ls
        echo "shared_preload_libraries = 'babelfishpg_tds,pgaudit'" | sudo tee -a /data/postgresql.conf
        echo "everything set"
        cd ~
        sudo PGPASSWORD=12345678 ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -h localhost -d jdbc_testdb -U jdbc_user -c "CREATE EXTENSION pgaudit;"
        sudo PGPASSWORD=12345678 ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -h localhost -d jdbc_testdb -U jdbc_user -c "ALTER SYSTEM SET pgaudit.log = 'all';"
        sudo ~/${{ inputs.install_dir }}/bin/pg_ctl -D ~/${{ inputs.install_dir }}/data restart
      shell: bash