name: 'Major Version Upgrade Utility'
inputs:
  engine_branch: 
    description: "Engine Branch"
    required: true
  extension_branch: 
    description: "Extension Branch"
    required: true
  is_final_ver:
    description: "Is this the final version"
    required: true
  pg_old_dir: 
    description: "Previous version was installed in this directory"
    required: true
  pg_new_dir:
    description: "Install new version in this directory"
    required: true
  migration_mode:
    description: "Database migration mode for Babelfish"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup latest version
      id: setup-new-version
      if: always()
      uses: ./.github/composite-actions/setup-new-version
      with:
        engine_branch: ${{ inputs.engine_branch }}
        extension_branch: ${{ inputs.extension_branch }}
        pg_new_dir: ${{ inputs.pg_new_dir }}

    - name: Run pg_upgrade
      id: run-pg_upgrade
      if: always() && steps.setup-new-version.outcome == 'success'
      uses: ./.github/composite-actions/run-pg-upgrade
      with: 
        migration_mode: ${{ inputs.migration_mode }}
        pg_old_dir: ${{ inputs.pg_old_dir }}
        pg_new_dir: ${{ inputs.pg_new_dir }}

    - name: Run Verify Tests
      if: always() && steps.run-pg_upgrade.outcome == 'success' && inputs.is_final_ver == 'true'
      uses: ./.github/composite-actions/run-verify-tests
      with:
        is_final_ver: ${{ inputs.is_final_ver }}
        pg_new_dir: ${{ inputs.pg_new_dir }}
        migration_mode: ${{ inputs.migration_mode }}