name: 'Build pg-hint-plan'

runs:
  using: "composite"
  steps:
    - name: Checkout, Build and Install pg-hint-plan
      run: |
        cd ..
        $GITHUB_WORKSPACE/.github/scripts/clone_pg_hint_plan_repo
        cd pg-hint-plan
        make
        make install
        make check
      shell: bash
