name: 'Build and Install PgAudit'

inputs:
  install_dir:
    description: 'Engine install directory'
    required: no
    default: psql
  branch: 
    description: 'Branch name which needs to checkout first'
    required: no
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Build and Install PgAudit
      run: |
        cd ~
        rm -rf pgaudit
        # Determine PgAudit version based on Babelfish branch
        if [[ "${{ inputs.branch }}" == "BABEL_5_X_DEV" ]]; then
          PGAUDIT_BRANCH="REL_17_STABLE"
          SED_LINE_NUMBER = 1517
        elif [[ "${{ inputs.branch }}" == "BABEL_4_X_DEV" ]]; then
          PGAUDIT_BRANCH = "REL_16_STABLE"
          SED_LINE_NUMBER = 1452
        else
          echo "Unsupported branch: ${{ inputs.branch }}"
          exit 1
        fi
        
        git clone --depth 1 --branch $PGAUDIT_BRANCH https://github.com/pgaudit/pgaudit.git
        cd pgaudit
        # adding the patch to fix BABEL-4600 to test in Github
        sed -i '${SED_LINE_NUMBER} s/^        else$/        else if (auditEventStack != NULL)/' pgaudit.c
        make install USE_PGXS=1 PG_CONFIG=~/psql/bin/pg_config 
        cd ../psql
        grep -i "shared_preload_libraries" data/postgresql.conf
        sudo sed -i 's/^shared_preload_libraries .*$/shared_preload_libraries = '\''babelfishpg_tds, pg_stat_statements,pgaudit'\''/g' data/postgresql.conf
        grep -i "shared_preload_libraries" data/postgresql.conf
        echo "everything set"

        ~/${{ inputs.install_dir }}/bin/pg_ctl -c -D ~/psql/data/ -l logfile restart
        sudo PGPASSWORD=12345678 ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -h localhost -d babelfish_db -U jdbc_user -c "CREATE EXTENSION pgaudit;"
        sudo PGPASSWORD=12345678 ~/${{ inputs.install_dir }}/bin/psql -v ON_ERROR_STOP=1 -h localhost -d babelfish_db -U jdbc_user -c "ALTER SYSTEM SET pgaudit.log = 'all';"

      shell: bash
      