name: 'Build PostGIS Extension'

inputs:
  install_dir:
    description: 'Engine install directory'
    required: no
    default: psql

runs:
  using: "composite"
  steps:
    - name: Build PostGIS Extension
      run: |
        cd ..
        sudo apt-get install wget
        wget http://postgis.net/stuff/postgis-3.3.3dev.tar.gz
        tar -xvzf postgis-3.3.3dev.tar.gz
        wget https://download.osgeo.org/proj/proj-4.9.1.tar.gz
        tar -xvzf proj-4.9.1.tar.gz
        cd proj-4.9.1
        if [ ! -d "build" ]; then
          mkdir build
        fi
        cd build
        cmake ..
        cmake --build .
        sudo cmake --build . --target install
        cd ../../postgis-3.3.3dev
        ./configure --without-protobuf --without-raster --with-pgconfig=$HOME/${{ inputs.install_dir }}/bin/pg_config
        make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config
        sudo make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config install
      shell: bash
