name: 'Build PostGIS Extension'

inputs:
  install_dir:
    description: 'Engine install directory'
    required: no
    default: psql

runs:
  using: "composite"
  steps:
    - name: Build PostGIS Extension
      run: |
        cd ..
        export CC='ccache gcc'
        export CMAKE_C_COMPILER_LAUNCHER=ccache
        export CMAKE_CXX_COMPILER_LAUNCHER=ccache 
        sudo apt-get install wget
        max_retries=20
        retries=0
        until [ $retries -ge $max_retries ]
        do
          wget http://postgis.net/stuff/postgis-3.4.0.tar.gz && break
          retries=$((retries+1))
        done
        tar -xvzf postgis-3.4.0.tar.gz
        retries1=0
        until [ $retries1 -ge $max_retries ]
        do
          wget https://download.osgeo.org/proj/proj-9.2.1.tar.gz && break
          retries1=$((retries1+1))
        done
        tar -xvzf proj-9.2.1.tar.gz
        cd proj-9.2.1
        if [ ! -d "build" ]; then
          mkdir build
        fi
        cd build
        cmake -DCMAKE_INSTALL_LIBDIR="lib/x86_64-linux-gnu" -DCMAKE_INSTALL_PREFIX="/usr" ..
        cmake --build .
        sudo cmake --build . --target install
        cd ../../postgis-3.4.0
        ./configure --without-protobuf --without-raster --with-pgconfig=$HOME/${{ inputs.install_dir }}/bin/pg_config
        make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config
        sudo make USE_PGXS=1 PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config install
      shell: bash
