name: 'Install Dependencies'
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: |
        cd ~
        echo 'Acquire::Retries "10";
        Acquire::https::Timeout "240";
        Acquire::http::Timeout "240";
        APT::Get::Assume-Yes "true";
        APT::Install-Recommends "false";
        APT::Install-Suggests "false";
        Debug::Acquire::https "true";
        ' | sudo tee -a /etc/apt/apt.conf.d/99custom
        sudo apt clean && sudo apt-get update --fix-missing -y
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update --fix-missing -y
        sudo apt-get install uuid-dev openjdk-8-jre libicu-dev libxml2-dev openssl libssl-dev python3-dev libossp-uuid-dev libpq-dev cmake pkg-config g++ build-essential bison mssql-tools unixodbc-dev libsybdb5 freetds-dev freetds-common
        sudo apt install -y ccache
        sudo /usr/sbin/update-ccache-symlinks
        echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
        source ~/.bashrc && echo $PATH
        echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      shell: bash

    - name: Restore ccache
      id: cache-compiler
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-${{ env.NOW }}
        restore-keys: |
          ccache-${{ runner.os }}