name: 'Run Dotnet tests'
description: 'Install and Run Babel Dotnet Tests'

runs:
  using: "composite"
  steps:
  - name: Install MSSQL Tools
    id: install-mssql-tools
    run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc
    shell: bash

  - name: Install Dotnet
    id: install-dotnet
    if: always() && steps.install-mssql-tools.outcome == 'success'
    run: | 
      cd ~
      wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get install -y apt-transport-https
      sudo apt-get install -y dotnet-sdk-5.0
      sudo apt-get install -y apt-transport-https
      sudo apt-get install -y aspnetcore-runtime-5.0
    shell: bash
          
  - name: Run Dotnet Tests
    if: always() && steps.install-dotnet.outcome == 'success'
    run: |
      cd test/dotnet
      dotnet build
      VSTEST_DISABLE_STANDARD_OUTPUT_CAPTURING=1 \
      babel_URL=localhost \
        babel_port=1433 \
        babel_databaseName=master \
        babel_user=jdbc_user \
        babel_password=12345678 \
        testName="all---TestUDD.txt;TestChar.txt;TestSqlVariant.txt;TestVarChar.txt;TestAuthentication.txt;TestText.txt" \
        dotnet test
    shell: bash
