-- Setup for StringInfo 1GB limit test
CREATE TABLE xml_limit_test (c1 VARCHAR(MAX));
GO
INSERT INTO xml_limit_test SELECT REPLICATE(CAST('X' AS VARCHAR(MAX)), 400000000);
GO
INSERT INTO xml_limit_test SELECT REPLICATE(CAST('X' AS VARCHAR(MAX)), 400000000);
GO
INSERT INTO xml_limit_test SELECT REPLICATE(CAST('X' AS VARCHAR(MAX)), 400000000);
GO
