DELETE FROM TAB_BABEL_3294_PREPARE WHERE C1 = 1;
GO

SELECT PRONAME FROM PG_PROC WHERE PRONAME = 'trig_babel_3294_prepare_for'
GO

DROP TRIGGER TRIG_BABEL_3294_PREPARE_FOR
GO

SELECT PRONAME FROM PG_PROC WHERE PRONAME = 'trig_babel_3294_prepare_for'
GO

DROP TRIGGER TRIG_BABEL_3294_PREPARE_AFTER
GO

DROP TABLE TAB_BABEL_3294_PREPARE
GO

