drop trigger nested_trigger_inside_proc_trig1
drop trigger nested_trigger_inside_proc_trig2
drop trigger nested_trigger_inside_proc_trig3
go

drop trigger nested_trigger_inside_proc_trig4
drop trigger nested_trigger_inside_proc_trig5
drop trigger nested_trigger_inside_proc_trig6
go

drop trigger nested_trigger_inside_proc_trig7
drop trigger nested_trigger_inside_proc_trig8
drop trigger nested_trigger_inside_proc_trig9
go

drop procedure nested_trigger_inside_proc_p1;
drop procedure nested_trigger_inside_proc_p2;
drop procedure nested_trigger_inside_proc_p3;
drop procedure nested_trigger_inside_proc_p01;
drop procedure nested_trigger_inside_proc_p02;
drop procedure nested_trigger_inside_proc_p03;
drop procedure nested_trigger_inside_proc_p001;
drop procedure nested_trigger_inside_proc_p002;
drop procedure nested_trigger_inside_proc_p003;



drop table nested_trigger_inside_proc_t1
drop table nested_trigger_inside_proc_t2
drop table nested_trigger_inside_proc_t3
go

