upgrade-version: [{
  upgrade-path: [
    {
      version: 16.1,
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{ upgrade-path: [
    {
      version: 16.2,
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{ upgrade-path: [
    {
      version: 16.3,
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{ upgrade-path: [
    {
      version: 16.4,
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{ upgrade-path: [
    {
      version: 16.6,
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
}
]