upgrade-version: [
{
  upgrade-path: [
    {
      version: source.latest,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ]
},
{
  upgrade-path: [
    {
      version: '15.15',
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ]
},
{
  upgrade-path: [
    {
      version: 16.8,
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
}
]