name: JDBC Upgrade Tests
on:
  push:
    branches:
      - BABEL_1_X_DEV
  pull_request:
    branches:
      - BABEL_1_X_DEV

jobs:
  extension-tests:
    env:
      ENGINE_VER_FROM: BABEL_1_0_0__PG_13_4
      EXTENSION_VER_FROM: BABEL_1_0_0
      ENGINE_VER_TO: BABEL_1_X_DEV__PG_13_6
      EXTENSION_VER_TO: BABEL_1_X_DEV

    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        id: install-dependencies
        if: always()
        uses: ./.github/composite-actions/install-dependencies

      - name: Clone, build, and run tests for Postgres engine using ${{env.ENGINE_VER_FROM}}
        id: build-modified-postgres-older
        if: always() && steps.install-dependencies.outcome == 'success'
        run: |
          cd ..
          git clone --branch $ENGINE_VER_FROM https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git 
          cd postgresql_modified_for_babelfish
          ./configure --prefix=$HOME/postgres/ --with-python PYTHON=/usr/bin/python2.7 --enable-debug CFLAGS="-ggdb" --with-libxml --with-uuid=ossp --with-icu
          make -j 4 2>error.txt
          make install
          make check
          cd contrib && make && sudo make install

      - name: Compile ANTLR
        id: compile-antlr
        if: always() && steps.build-modified-postgres-older.outcome == 'success'
        uses: ./.github/composite-actions/compile-antlr

      - uses: actions/checkout@v2
        with:
          repository: babelfish-for-postgresql/babelfish_extensions
          ref: ${{env.EXTENSION_VER_FROM}}
      
      - name: Build Extensions using ${{env.EXTENSION_VER_FROM}}
        id: build-extensions-older
        if: always() && steps.compile-antlr.outcome == 'success'
        uses: ./.github/composite-actions/build-extensions

      - name: Install extensions using ${{env.EXTENSION_VER_FROM}}
        id: install-extensions-older
        if: always() && steps.build-extensions-older.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions
        
      - name: Clone, build, and run tests for Postgres engine using ${{env.ENGINE_VER_TO}}
        id: build-modified-postgres-newer
        if: always() && steps.install-extensions-older.outcome == 'success'
        run: |
          cd ../postgresql_modified_for_babelfish
          git checkout ${{env.ENGINE_VER_TO}}
          ./configure --prefix=$HOME/postgres/ --with-python PYTHON=/usr/bin/python2.7 --enable-debug CFLAGS="-ggdb" --with-libxml --with-uuid=ossp --with-icu
          make clean
          make -j 4 2>error.txt
          make install
          make check
          cd contrib && make && sudo make install

      - uses: actions/checkout@v2
        with:
          repository: babelfish-for-postgresql/babelfish_extensions
          ref: ${{env.EXTENSION_VER_TO}}

      - name: Build Extensions using ${{env.EXTENSION_VER_TO}}
        id: build-extensions-newer
        if: always() && steps.build-modified-postgres-newer.outcome == 'success'
        uses: ./.github/composite-actions/build-extensions

      - name: Update extensions
        id: update-extensions
        if: always() && steps.build-extensions-newer.outcome == 'success'
        run: |
          cd ~
          ~/postgres/bin/pg_ctl -D ~/postgres/data/ -l logfile restart
          sudo ~/postgres/bin/psql -d jdbc_testdb -U runner -c "\dx"
          sudo ~/postgres/bin/psql -d jdbc_testdb -U runner -c "ALTER EXTENSION "babelfishpg_common" UPDATE; ALTER EXTENSION "babelfishpg_tsql" UPDATE;"
          sudo ~/postgres/bin/psql -d jdbc_testdb -U runner -c "\dx"
          sqlcmd -S localhost -U jdbc_user -P 12345678 -Q "SELECT @@version GO"

      - name: Run JDBC Tests
        id: jdbc
        if: always() && steps.update-extensions.outcome == 'success'
        timeout-minutes: 15
        run: |
          cd test/JDBC/
          mvn test
      
      - name: Upload Log
        if: always() && steps.jdbc.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: postgres-log
          path: ~/postgres/data/logfile
      
      # The test summary files contain paths with ':' characters, which is not allowed with the upload-artifact actions
      - name: Rename Test Summary Files
        id: test-file-rename
        if: always() && steps.jdbc.outcome == 'failure'
        run: |
          cd test/JDBC/Info
          timestamp=`ls -Art | tail -n 1`
          cd $timestamp
          mv $timestamp.diff ../output-diff.diff
          mv "$timestamp"_runSummary.log ../run-summary.log
      
      - name: Upload Run Summary 
        if: always() && steps.test-file-rename == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: run-summary.log
          path: test/JDBC/Info/run-summary.log
      
      - name: Upload Output Diff
        if: always() && steps.jdbc.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: output-diff.diff
          path: test/JDBC/Info/output-diff.diff
