name: Major Version Upgrade Verification tests
on: [push, pull_request]

jobs:
  run-babelfish-mvu-verification-tests:
    env:
      OLD_INSTALL_DIR: postgres13
      NEW_INSTALL_DIR: postgres14
      ENGINE_BRANCH_FROM: BABEL_1_X_DEV__PG_13_6
      EXTENSION_BRANCH_FROM: BABEL_1_X_DEV

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        id: install-dependencies
        if: always()
        uses: ./.github/composite-actions/install-dependencies

      - name: Build Modified Postgres using ${{env.ENGINE_BRANCH_FROM}}
        id: build-modified-postgres-old
        if: always() && steps.install-dependencies.outcome == 'success'
        run: |
          cd ..
          git clone --branch ${{env.ENGINE_BRANCH_FROM}} https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git
          cd postgresql_modified_for_babelfish
          ./configure --prefix=$HOME/${{env.OLD_INSTALL_DIR}} --with-python PYTHON=/usr/bin/python2.7 --enable-debug CFLAGS="-ggdb" --with-libxml --with-uuid=ossp --with-icu
          make clean
          make -j 4 2>error.txt
          make install
          make check
          cd contrib && make && sudo make install
        shell: bash

      - name: Compile ANTLR
        id: compile-antlr
        if: always() && steps.build-modified-postgres-old.outcome == 'success'
        uses: ./.github/composite-actions/compile-antlr
        with:
          install_dir: ${{env.OLD_INSTALL_DIR}}

      - uses: actions/checkout@v2
        with:
          repository: babelfish-for-postgresql/babelfish_extensions
          ref: ${{env.EXTENSION_BRANCH_FROM}}

      - name: Build Extensions using ${{env.EXTENSION_BRANCH_FROM}}
        id: build-extensions-old
        if: always() && steps.compile-antlr.outcome == 'success'
        run: |
          export PG_CONFIG=~/${{env.OLD_INSTALL_DIR}}/bin/pg_config
          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
          export cmake=$(which cmake)
          cd contrib/babelfishpg_money
          make && make install
          cd ../babelfishpg_common
          make && make install
          cd ../babelfishpg_tds
          make && make install
          cd ../babelfishpg_tsql
          make && make install
      
      - name: Install Extensions using ${{env.EXTENSION_BRANCH_FROM}}
        id: install-extensions-old
        if: always() && steps.build-extensions-old.outcome == 'success'
        run: |
          cd ~
          export PATH=/opt/mssql-tools/bin:$PATH
          ~/${{env.OLD_INSTALL_DIR}}/bin/initdb -D ~/${{env.OLD_INSTALL_DIR}}/data
          ~/${{env.OLD_INSTALL_DIR}}/bin/pg_ctl -D ~/${{env.OLD_INSTALL_DIR}}/data -l logfile13 start
          cd ${{env.OLD_INSTALL_DIR}}/data
          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
          sudo sed -i "s/#shared_preload_libraries = ''/shared_preload_libraries = 'babelfishpg_tds'/g" postgresql.conf
          ipaddress=$(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}')
          sudo echo "host    all             all             $ipaddress/32            trust" >> pg_hba.conf
          ~/${{env.OLD_INSTALL_DIR}}/bin/pg_ctl -D ~/${{env.OLD_INSTALL_DIR}}/data -l logfile13 restart
          cd ~/work/babelfish_extensions/babelfish_extensions/
          sudo ~/${{env.OLD_INSTALL_DIR}}/bin/psql -d postgres -U runner -v user="jdbc_user" -v db="jdbc_testdb" -f .github/scripts/create_extension.sql
          sudo ~/${{env.OLD_INSTALL_DIR}}/bin/psql -d jdbc_testdb -U runner -c "ALTER SYSTEM SET babelfishpg_tsql.migration_mode = 'multi-db';"
          sudo ~/${{env.OLD_INSTALL_DIR}}/bin/psql -d jdbc_testdb -U runner -c "SELECT pg_reload_conf();"
          sqlcmd -S localhost -U jdbc_user -P 12345678 -Q "SELECT @@version GO"
        shell: bash

      - uses: actions/checkout@v2

      - name: Run JDBC preparation tests on old server
        id: run-preparation-test
        if: always() && steps.install-extensions-old.outcome == 'success'
        run: |
          cd test/JDBC/
          export inputFilesPath=upgrade/preparation
          mvn test

      - name: Build Modified Postgres using latest version
        id: build-modified-postgres-new
        if: always() && steps.run-preparation-test.outcome == 'success'
        uses: ./.github/composite-actions/build-modified-postgres
        with:
          install_dir: ${{env.NEW_INSTALL_DIR}}

      - name: Copy ANTLR
        run: cp "/usr/local/lib/libantlr4-runtime.so.4.9.3" ~/${{env.NEW_INSTALL_DIR}}/lib/

      - name: Build Extensions using latest version
        id: build-extensions-new
        if: always() && steps.build-modified-postgres-new.outcome == 'success'
        uses: ./.github/composite-actions/build-extensions
        with:
          install_dir: ${{env.NEW_INSTALL_DIR}}

      - name: Setup new data directory
        id: setup-new-datadir
        if: always() && steps.build-extensions-new.outcome == 'success'
        run: |
          cd ~
          ~/${{env.NEW_INSTALL_DIR}}/bin/initdb -D ~/${{env.NEW_INSTALL_DIR}}/data
          cd ~/${{env.NEW_INSTALL_DIR}}/data
          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
          sudo sed -i "s/#shared_preload_libraries = ''/shared_preload_libraries = 'babelfishpg_tds'/g" postgresql.conf
          ipaddress=$(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}')
          sudo echo "host    all             all             $ipaddress/32            trust" >> pg_hba.conf
        shell: bash

      - name: Run pg_upgrade
        id: run-pg_upgrade
        if: always() && steps.setup-new-datadir.outcome == 'success'
        uses: ./.github/composite-actions/run-pg-upgrade
        with:
          migration_mode: 'multi-db'

      - name: Run JDBC verification tests on upgraded server
        id: run-verification-test
        if: always() && steps.run-pg_upgrade.outcome == 'success'
        run: |
          cd test/JDBC/
          export inputFilesPath=upgrade/verification
          mvn test

      - name: Rename Test Summary Files
        id: test-file-rename
        if: always() && (steps.run-preparation-test.outcome == 'failure' || steps.run-verification-test.outcome == 'failure')
        run: |
          cd test/JDBC/Info
          timestamp=`ls -Art | tail -n 1`
          cd $timestamp
          mkdir -p ~/upgrade
          mv $timestamp.diff ~/upgrade/output-diff.diff
          mv "$timestamp"_runSummary.log ~/upgrade/run-summary.log

      - name: Upload Logs
        if: always() && steps.test-file-rename.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: upgrade-logs
          path: |
            ~/upgrade/*.log
            ~/upgrade/*.diff
            ~/${{env.OLD_INSTALL_DIR}}/data/logfile13
            ~/${{env.NEW_INSTALL_DIR}}/data/logfile14
