# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commiter:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Alias of the commiter'
        # Default value if no value is explicitly provided
        default: 'nirmisha'
        # Input has to be provided for the workflow to run
        required: true
      target_branch:
        description: 'Branch Where to do version bump'
        default: 'BABEL_2_X_DEV'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Auto-Bump-Version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      EXT_BRANCH_URL: https://github.com/shah-nirmit/babelfish_extensions
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout the repo
          id: checkout-fork
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: add the remote and setup tracking branch
          id: setup-tr-branch
          run: |
            git remote add upstream ${{ env.EXT_BRANCH_URL }}
            git fetch upstream
            git checkout -b bump-version-${{ github.event.inputs.target_branch}} upstream/${{ github.event.inputs.target_branch}}
            git status
            git branch -vv
            #        - name: Identify the version to bump
            #          id: identify-versions
            #          run: |
            #            vfile=contrib/babelfishpg_tsql/src/babelfish_version.h
            #            # bump babelfish internal version
            #            bbf_int_pre_version=$(awk '/BABELFISH_INTERNAL_VERSION_STR/ {print $4}' $vfile | sed 's/\"//')
            #            echo "bbf_int_old_version=$bbf_int_pre_version" >> $GITHUB_ENV
            #            bbf_int_new_version=$(awk -F'[ ."]' '/^#define BABELFISH_INT/ {print $5"."$6"."$7+1"."$8}' $vfile )
            #            echo "bbf_int_new_version=$bbf_int_new_version" >> $GITHUB_ENV
            #            # bump babelfish version
            #            bbf_pre_version=$(awk '/BABELFISH_VERSION_STR/ {print $3}' $vfile | sed 's/\"//')
            #            echo "bbf_old_version=$bbf_pre_version" >> $GITHUB_ENV
            #            bbf_new_version=$( awk -F'[ ."]' '/^#define BABELFISH_VER/ {print $4"."$5"."$6+1}' $vfile)
            #            echo "bbf_new_version=$bbf_new_version" >> $GITHUB_ENV
            #
            #        - name: Test vars
            #          run: |
            #            echo ${{ env.bbf_new_version }}
            #            echo ${{ env.bbf_int_new_version }}
            #        - name: Make a new branch and make a commit to bump version
            #          run: |
            #            git config --global user.email "Github-Actions-bot@example.com"
            #            git config --global user.name "Github-Actions-bot"
            #            vfile=contrib/babelfishpg_tsql/src/babelfish_version.h
            #            git checkout -b bump-ver-${{ env.bbf_new_version }}
            #            sed -i -r 's/(.*)(BABELFISH_INTERNAL_VERSION_STR )"(Babelfish )([0-9]+.[0-9]+.)([0-9]+)(.[0-9]+)"/echo "\1\2\\"\3\4$((\5+1))\6\\""/ge' $vfile
            #            sed -i -r 's/(.*)(BABELFISH_VERSION_STR )"([0-9]+.[0-9]+.)([0-9]+)"/echo "\1\2\\"\3$((\4+1))\\""/ge' $vfile
            #            git diff
            #            git add .
            #            git commit -m "Bump Babelfish Version to ${{ env.bbf_new_version }}"
            #            git push -u origin bump-ver-${{ env.bbf_new_version }}
            #
            #        - name: Raise a PR
            #          run: |
            #            gh pr create --title "Bump Babelfish Version to ${{ env.bbf_new_version }}" --repo shah-nirmit/babelfish_extensions --base ${{ github.event.inputs.target_branch }} \
            #                                  --body "Bump Babelfish Internal Version and Babelfish Version"
        - name: Bump the Version and push to branch
          id: bump-ver
          run: |
            $GITHUB_WORKSPACE/.github/scripts/bump-version.sh
            git log
