name: Tests
on: [push, pull_request]

jobs:
  run-jdbc-tests:
    name: JDBC Tests
    uses: ./.github/workflows/jdbc-tests.yml
  
  run-odbc-tests:
    name: ODBC Tests
    uses: ./.github/workflows/odbc-tests.yml
  
  run-dotnet-tests:
    name: Dotnet Tests
    uses: ./.github/workflows/dotnet-tests.yml

  run-python-tests:
    name: Python Tests
    uses: ./.github/workflows/python-tests.yml

  run-isolation-tests:
    name: Isolation Tests
    uses: ./.github/workflows/isolation-tests.yml

  run-babelfish-code-coverage-for-pull_request:
    needs: [run-jdbc-tests, run-odbc-tests, run-dotnet-tests, run-python-tests, run-isolation-tests]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      id: checkout
    
    - name: Install Code Coverage Dependencies
      id: install-code-coverage-dependencies
      if: always()
      run: |
        sudo apt-get install lcov
    
    - name: Download Coverage Reports
      uses: actions/download-artifact@v4
      with:
        pattern: coverage-babelfish-extensions-*
        path: contrib/
        merge-multiple: true

    - name: Generate Overall Code Coverage
      id: generate-total-code-coverage
      if: success()
      run: |
        cd contrib/
        # Combine all coverage files
        lcov $(for f in *-lcov.info; do echo "-a $f "; done) -o lcov.info
        # Generate coverage report
        lcov --list lcov.info
      shell: bash

    - name: Upload coverage to Coveralls
      if: success()
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: contrib/lcov.info
        parallel: true
        flag-name: ${{ github.job }}

  finish-coverage:
    needs: run-babelfish-code-coverage-for-pull_request
    runs-on: ubuntu-22.04
    steps:
    - name: Finish Coveralls parallel build
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

env:
    COVERALLS_DEBUG: true  # Enable debug output
    COVERALLS_ENDPOINT: https://coveralls.io
    COVERALLS_SERVICE_NAME: github
