name: Static Code Analyzer
on: [push, pull_request]

jobs:
  run-static-code-analyzer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Install cppcheck
        id: install-cppcheck
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install cppcheck=2.7-1
          cppcheck --version

      - name: Clone engine repository
        id: clone-engine-repo
        if: always() && steps.install-cppcheck.outcome == 'success'
        run: |
          cd ..
          rm -rf postgresql_modified_for_babelfish

          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            ENGINE_BRANCH=$GITHUB_HEAD_REF
          else
            ENGINE_BRANCH=$GITHUB_REF_NAME
          fi

          $GITHUB_WORKSPACE/.github/scripts/clone_engine_repo "$GITHUB_REPOSITORY_OWNER" "$ENGINE_BRANCH"

      - name: Run cppcheck on extensions
        id: run-cppcheck
        if: always()
        run: |
          cppcheck --error-exitcode=-1 -j 16 --template=gcc \
          --enable=warning --inline-suppr \
          ./contrib -I ../postgresql_modified_for_babelfish \
          --suppress=nullPointerRedundantCheck \
          --output-file=cppcheck-failures.txt
      
      - name: Upload failures as artifacts
        id: upload-failures
        if: always() && steps.run-cppcheck.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-failures
          path: ./cppcheck-failures.txt
